[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
buildCommand = "pip install -r requirements.txt"
startCommand = "python api_server_unified.py"
healthcheckPath = "/health"
healthcheckTimeout = 300

[[services]]
name = "frontend"
rootDirectory = "flash-frontend-apple"
buildCommand = "npm install && npm run build"
startCommand = "npm start"
port = 3000