global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'flash-monitor'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  # FLASH API metrics
  - job_name: 'flash-api'
    static_configs:
      - targets: ['api:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

# Recording rules for common queries
# Create alerts.yml for alerting rules like:
# - High latency (p99 > 500ms)
# - High error rate (> 5%)
# - Low cache hit rate (< 50%)
# - Narrow prediction range (std < 0.1)