
# Additional frameworks added by expansion script

    "porters_generic_strategies": Framework(
        id="porters_generic_strategies",
        name="Porter's Generic Strategies",
        description="Framework for achieving competitive advantage through cost leadership, differentiation, or focus",
        category=FrameworkCategory.STRATEGY,
        subcategory="Competitive Strategy",
        when_to_use=[
            "Defining competitive strategy",
            "Market positioning decisions",
            "Strategic planning",
            "Business unit strategy",
            "Competitive advantage development",
        ],
        key_components=[
            "Cost Leadership",
            "Differentiation",
            "Cost Focus",
            "Differentiation Focus",
            "Stuck in the middle risk",
        ],
        application_steps=[
            "Analyze industry structure",
            "Assess company capabilities",
            "Choose primary strategy",
            "Align operations to strategy",
            "Build required competencies",
            "Monitor competitive position",
            "Avoid stuck in the middle",
        ],
        expected_outcomes=[
            "Clear strategic direction",
            "Competitive advantage",
            "Focused resource allocation",
            "Market positioning",
            "Sustainable profitability",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Market analysis",
            "Capability assessment",
        ],
        complementary_frameworks=[
            "porters_five_forces",
            "value_chain_analysis",
        ],
        time_to_implement="2-3 months",
        resources_required=[
            "Strategy team",
            "Market research",
            "Financial analysis",
        ],
    ),

    "vrio_framework": Framework(
        id="vrio_framework",
        name="VRIO Framework",
        description="Resource-based view framework assessing if resources are Valuable, Rare, Inimitable, and Organized",
        category=FrameworkCategory.STRATEGY,
        subcategory="Resource Analysis",
        when_to_use=[
            "Competitive advantage analysis",
            "Resource evaluation",
            "Strategic capability assessment",
            "M&A due diligence",
            "Core competency identification",
        ],
        key_components=[
            "Value (economic value)",
            "Rarity (scarcity)",
            "Imitability (difficulty to copy)",
            "Organization (ability to exploit)",
            "Competitive implications",
        ],
        application_steps=[
            "Identify key resources and capabilities",
            "Evaluate value creation potential",
            "Assess rarity in market",
            "Analyze imitability barriers",
            "Review organizational readiness",
            "Determine competitive advantage",
            "Develop protection strategies",
        ],
        expected_outcomes=[
            "Resource-based advantages identified",
            "Competitive position clarity",
            "Investment priorities",
            "Capability development plan",
            "Sustainable advantage strategies",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Resource inventory",
            "Competitive intelligence",
        ],
        time_to_implement="2-4 weeks",
        resources_required=[
            "Strategy team",
            "Resource audit",
            "Competitive analysis",
        ],
    ),

    "scenario_planning": Framework(
        id="scenario_planning",
        name="Scenario Planning",
        description="Strategic planning method using multiple future scenarios to develop flexible strategies",
        category=FrameworkCategory.STRATEGY,
        subcategory="Strategic Planning",
        when_to_use=[
            "High uncertainty environments",
            "Long-term strategic planning",
            "Risk management",
            "Innovation strategy",
            "Major investment decisions",
        ],
        key_components=[
            "Driving forces",
            "Critical uncertainties",
            "Scenario narratives",
            "Early indicators",
            "Strategic options",
            "Contingency plans",
        ],
        application_steps=[
            "Identify driving forces of change",
            "Determine critical uncertainties",
            "Develop scenario logics",
            "Create scenario narratives",
            "Assess implications for strategy",
            "Develop strategic options",
            "Monitor early indicators",
        ],
        expected_outcomes=[
            "Future-ready strategies",
            "Risk mitigation",
            "Strategic flexibility",
            "Early warning system",
            "Robust decision making",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "All industries",
            "Especially volatile sectors",
        ],
        prerequisites=[
            "Environmental scanning",
            "Strategic thinking capability",
        ],
        complementary_frameworks=[
            "strategic_foresight",
            "real_options",
        ],
        time_to_implement="3-6 months",
        resources_required=[
            "Scenario team",
            "External experts",
            "Research resources",
        ],
    ),

    "ge_mckinsey_matrix": Framework(
        id="ge_mckinsey_matrix",
        name="GE-McKinsey Matrix",
        description="Portfolio analysis tool using industry attractiveness and business unit strength",
        category=FrameworkCategory.STRATEGY,
        subcategory="Portfolio Management",
        when_to_use=[
            "Portfolio optimization",
            "Investment decisions",
            "Resource allocation",
            "Divestment planning",
            "Strategic prioritization",
        ],
        key_components=[
            "Industry attractiveness factors",
            "Business unit strength factors",
            "Nine-box matrix",
            "Investment strategies",
            "Portfolio balance",
        ],
        application_steps=[
            "Define attractiveness criteria",
            "Define strength criteria",
            "Score each business unit",
            "Plot on nine-box matrix",
            "Analyze portfolio balance",
            "Develop unit strategies",
            "Allocate resources accordingly",
        ],
        expected_outcomes=[
            "Optimized portfolio",
            "Clear investment priorities",
            "Resource allocation guide",
            "Exit strategies identified",
            "Balanced risk-return",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "Diversified companies",
            "Conglomerates",
        ],
        prerequisites=[
            "Multi-business portfolio",
            "Market data",
            "Performance metrics",
        ],
        complementary_frameworks=[
            "bcg_growth_share_matrix",
            "portfolio_optimization",
        ],
        time_to_implement="4-6 weeks",
        resources_required=[
            "Strategy team",
            "Business unit data",
            "Market analysis",
        ],
    ),

    "core_competence": Framework(
        id="core_competence",
        name="Core Competence Framework",
        description="Framework for identifying and leveraging organizational capabilities that provide competitive advantage",
        category=FrameworkCategory.STRATEGY,
        subcategory="Capability Strategy",
        when_to_use=[
            "Strategic planning",
            "Diversification decisions",
            "Outsourcing evaluation",
            "Partnership strategy",
            "Innovation focus",
        ],
        key_components=[
            "Customer value test",
            "Competitor differentiation test",
            "Extendability test",
            "Core competence identification",
            "Competence development",
        ],
        application_steps=[
            "Map organizational capabilities",
            "Apply three tests to each",
            "Identify core competencies",
            "Link to products/services",
            "Assess competitive advantage",
            "Plan competence development",
            "Leverage across business",
        ],
        expected_outcomes=[
            "Core competencies identified",
            "Strategic focus",
            "Innovation direction",
            "Outsourcing decisions",
            "Competitive advantage",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Capability mapping",
            "Competitive analysis",
        ],
        complementary_frameworks=[
            "vrio_framework",
            "value_chain_analysis",
        ],
        time_to_implement="3-4 weeks",
        resources_required=[
            "Strategy team",
            "Capability audit",
            "Competitive intelligence",
        ],
    ),

    "innovation_ambition_matrix": Framework(
        id="innovation_ambition_matrix",
        name="Innovation Ambition Matrix",
        description="Framework for balancing innovation portfolio across core, adjacent, and transformational initiatives",
        category=FrameworkCategory.INNOVATION,
        subcategory="Innovation Portfolio",
        when_to_use=[
            "Innovation portfolio planning",
            "R&D resource allocation",
            "Risk balancing",
            "Growth strategy",
            "Innovation metrics",
        ],
        key_components=[
            "Core innovations (existing products/markets)",
            "Adjacent innovations (expand from existing)",
            "Transformational innovations (new offerings/markets)",
            "70-20-10 rule",
            "Risk-return balance",
        ],
        application_steps=[
            "Map current innovation projects",
            "Categorize by ambition level",
            "Analyze current portfolio mix",
            "Define optimal balance",
            "Adjust resource allocation",
            "Manage by different metrics",
            "Monitor portfolio performance",
        ],
        expected_outcomes=[
            "Balanced innovation portfolio",
            "Appropriate risk levels",
            "Resource optimization",
            "Clear innovation strategy",
            "Improved ROI",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Innovation pipeline",
            "Strategic goals",
            "Risk appetite",
        ],
        complementary_frameworks=[
            "stage_gate_process",
            "innovation_metrics",
        ],
        time_to_implement="2-3 weeks",
        resources_required=[
            "Innovation team",
            "Portfolio data",
            "Strategy alignment",
        ],
    ),

    "business_model_innovation": Framework(
        id="business_model_innovation",
        name="Business Model Innovation",
        description="Framework for systematically innovating how a company creates, delivers, and captures value",
        category=FrameworkCategory.INNOVATION,
        subcategory="Business Model Design",
        when_to_use=[
            "Market disruption",
            "New venture creation",
            "Digital transformation",
            "Competitive threats",
            "Growth initiatives",
        ],
        key_components=[
            "Value proposition innovation",
            "Revenue model innovation",
            "Cost structure innovation",
            "Value network innovation",
            "Customer relationship innovation",
        ],
        application_steps=[
            "Map current business model",
            "Identify innovation opportunities",
            "Generate new model concepts",
            "Prototype and test models",
            "Analyze feasibility",
            "Plan transition approach",
            "Implement and scale",
        ],
        expected_outcomes=[
            "New business models",
            "Competitive differentiation",
            "New revenue streams",
            "Market disruption",
            "Sustainable advantage",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Market understanding",
            "Innovation capability",
            "Change readiness",
        ],
        complementary_frameworks=[
            "business_model_canvas",
            "value_innovation",
        ],
        time_to_implement="3-6 months",
        resources_required=[
            "Innovation team",
            "Business modeling tools",
            "Pilot resources",
        ],
    ),

    "disruptive_innovation": Framework(
        id="disruptive_innovation",
        name="Disruptive Innovation Theory",
        description="Framework for understanding how simpler, cheaper innovations can disrupt established markets",
        category=FrameworkCategory.INNOVATION,
        subcategory="Innovation Strategy",
        when_to_use=[
            "Market entry strategy",
            "Competitive response",
            "Innovation planning",
            "Business model design",
            "Technology strategy",
        ],
        key_components=[
            "Low-end disruption",
            "New-market disruption",
            "Sustaining innovation",
            "Performance trajectories",
            "Value network shift",
        ],
        application_steps=[
            "Analyze market over/underserved segments",
            "Identify disruption opportunities",
            "Design simpler solutions",
            "Target non-consumption",
            "Build new value network",
            "Improve performance over time",
            "Move upmarket strategically",
        ],
        expected_outcomes=[
            "Disruption opportunities identified",
            "New market creation",
            "Competitive advantage",
            "Growth strategy",
            "Innovation focus",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "Technology",
            "All industries facing disruption",
        ],
        prerequisites=[
            "Market analysis",
            "Innovation capability",
            "Patient capital",
        ],
        complementary_frameworks=[
            "blue_ocean_strategy",
            "jobs_to_be_done",
        ],
        time_to_implement="6-12 months",
        resources_required=[
            "Innovation team",
            "Market research",
            "Development resources",
        ],
    ),

    "innovation_ecosystem": Framework(
        id="innovation_ecosystem",
        name="Innovation Ecosystem Framework",
        description="Framework for building and managing networks of partners for collaborative innovation",
        category=FrameworkCategory.INNOVATION,
        subcategory="Open Innovation",
        when_to_use=[
            "Building innovation networks",
            "Platform strategies",
            "Ecosystem development",
            "Collaborative R&D",
            "Innovation acceleration",
        ],
        key_components=[
            "Ecosystem actors",
            "Value exchanges",
            "Governance mechanisms",
            "Platform architecture",
            "Network effects",
            "Ecosystem health metrics",
        ],
        application_steps=[
            "Map ecosystem stakeholders",
            "Define value propositions",
            "Design interaction mechanisms",
            "Establish governance rules",
            "Build platform infrastructure",
            "Attract and onboard partners",
            "Manage ecosystem dynamics",
        ],
        expected_outcomes=[
            "Thriving innovation ecosystem",
            "Accelerated innovation",
            "Network effects",
            "Shared value creation",
            "Competitive moat",
        ],
        complexity=ComplexityLevel.EXPERT,
        industry_relevance=[
            "Technology",
            "Platform businesses",
            "R&D intensive",
        ],
        prerequisites=[
            "Platform thinking",
            "Partner management",
            "Long-term vision",
        ],
        complementary_frameworks=[
            "open_innovation",
            "platform_strategy",
        ],
        time_to_implement="12-24 months",
        resources_required=[
            "Ecosystem team",
            "Platform technology",
            "Partner incentives",
        ],
    ),

    "reverse_innovation": Framework(
        id="reverse_innovation",
        name="Reverse Innovation",
        description="Framework for developing innovations in emerging markets that flow back to developed markets",
        category=FrameworkCategory.INNOVATION,
        subcategory="Global Innovation",
        when_to_use=[
            "Emerging market entry",
            "Cost innovation needs",
            "Global product strategy",
            "Market disruption",
            "Inclusive innovation",
        ],
        key_components=[
            "Local market immersion",
            "Clean-slate design",
            "Price-performance innovation",
            "Reverse flow mechanisms",
            "Glocalization balance",
        ],
        application_steps=[
            "Immerse in local market needs",
            "Forget developed market assumptions",
            "Design for local constraints",
            "Innovate on price-performance",
            "Test and refine locally",
            "Identify reverse flow opportunities",
            "Adapt for developed markets",
        ],
        expected_outcomes=[
            "Emerging market success",
            "Cost innovations",
            "Global product portfolio",
            "Market disruption potential",
            "New growth avenues",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "Multinational corporations",
            "Global businesses",
        ],
        prerequisites=[
            "Global presence",
            "Local market knowledge",
            "Innovation flexibility",
        ],
        complementary_frameworks=[
            "frugal_innovation",
            "glocalization",
        ],
        time_to_implement="6-12 months",
        resources_required=[
            "Local innovation teams",
            "Market research",
            "Development resources",
        ],
    ),

    "growth_hacking": Framework(
        id="growth_hacking",
        name="Growth Hacking Framework",
        description="Data-driven experimentation approach to rapidly test and scale growth tactics",
        category=FrameworkCategory.GROWTH,
        subcategory="Growth Experimentation",
        when_to_use=[
            "Rapid growth needs",
            "Limited marketing budget",
            "Digital products",
            "User acquisition",
            "Startup growth",
        ],
        key_components=[
            "Growth hypothesis",
            "Rapid experimentation",
            "Data-driven decisions",
            "Scalable tactics",
            "Cross-functional approach",
            "Growth metrics focus",
        ],
        application_steps=[
            "Define growth metrics",
            "Generate growth ideas",
            "Prioritize experiments",
            "Run rapid tests",
            "Analyze results",
            "Scale what works",
            "Kill what doesn't",
        ],
        expected_outcomes=[
            "Accelerated growth",
            "Lower acquisition costs",
            "Scalable tactics identified",
            "Data-driven culture",
            "Efficient resource use",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "Startups",
            "Digital businesses",
            "SaaS",
        ],
        prerequisites=[
            "Analytics infrastructure",
            "Experimentation culture",
            "Agile processes",
        ],
        complementary_frameworks=[
            "aarrr_metrics",
            "lean_startup",
        ],
        time_to_implement="Ongoing process",
        resources_required=[
            "Growth team",
            "Analytics tools",
            "Testing infrastructure",
        ],
    ),

    "network_effects": Framework(
        id="network_effects",
        name="Network Effects Framework",
        description="Framework for building and leveraging value that increases as more users join the network",
        category=FrameworkCategory.GROWTH,
        subcategory="Platform Growth",
        when_to_use=[
            "Platform businesses",
            "Marketplace development",
            "Social products",
            "Ecosystem building",
            "Competitive moats",
        ],
        key_components=[
            "Direct network effects",
            "Indirect network effects",
            "Local vs global effects",
            "Same-side vs cross-side",
            "Network density",
            "Switching costs",
        ],
        application_steps=[
            "Identify network effect types",
            "Design for network value",
            "Solve chicken-egg problem",
            "Build critical mass",
            "Strengthen network effects",
            "Create switching costs",
            "Defend against multi-homing",
        ],
        expected_outcomes=[
            "Exponential value growth",
            "Competitive moat",
            "User lock-in",
            "Market dominance",
            "Valuation premium",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "Platform businesses",
            "Marketplaces",
            "Social networks",
        ],
        prerequisites=[
            "Platform architecture",
            "User base",
            "Value proposition",
        ],
        complementary_frameworks=[
            "platform_strategy",
            "ecosystem_design",
        ],
        time_to_implement="6-12 months",
        resources_required=[
            "Product team",
            "Platform infrastructure",
            "User acquisition",
        ],
    ),

    "cohort_analysis": Framework(
        id="cohort_analysis",
        name="Cohort Analysis Framework",
        description="Method for analyzing user behavior by grouping them into cohorts based on shared characteristics",
        category=FrameworkCategory.GROWTH,
        subcategory="Growth Analytics",
        when_to_use=[
            "Retention analysis",
            "LTV calculation",
            "Product improvements",
            "Growth optimization",
            "Churn reduction",
        ],
        key_components=[
            "Cohort definition",
            "Time-based cohorts",
            "Behavior-based cohorts",
            "Retention curves",
            "Revenue cohorts",
            "Cohort comparison",
        ],
        application_steps=[
            "Define cohort criteria",
            "Segment users into cohorts",
            "Track cohort metrics over time",
            "Visualize retention curves",
            "Identify patterns and trends",
            "Compare cohort performance",
            "Act on insights",
        ],
        expected_outcomes=[
            "Retention insights",
            "LTV improvements",
            "Product-market fit signals",
            "Growth optimization",
            "Churn reduction",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "SaaS",
            "E-commerce",
            "Apps",
            "Subscription businesses",
        ],
        prerequisites=[
            "User tracking",
            "Analytics tools",
            "Historical data",
        ],
        complementary_frameworks=[
            "aarrr_metrics",
            "unit_economics",
        ],
        time_to_implement="1-2 weeks",
        resources_required=[
            "Analytics tools",
            "Data analyst",
            "Visualization software",
        ],
    ),

    "freemium_model": Framework(
        id="freemium_model",
        name="Freemium Model Framework",
        description="Framework for designing and optimizing free-to-paid user conversion strategies",
        category=FrameworkCategory.GROWTH,
        subcategory="Monetization Strategy",
        when_to_use=[
            "SaaS monetization",
            "User acquisition",
            "Product-led growth",
            "Market penetration",
            "Upsell strategies",
        ],
        key_components=[
            "Free tier design",
            "Premium features",
            "Conversion triggers",
            "Usage limits",
            "Value demonstration",
            "Upgrade paths",
        ],
        application_steps=[
            "Define free tier value",
            "Identify premium features",
            "Set usage limits strategically",
            "Design conversion triggers",
            "Create upgrade paths",
            "Optimize pricing tiers",
            "Monitor conversion metrics",
        ],
        expected_outcomes=[
            "User base growth",
            "Conversion optimization",
            "Revenue growth",
            "Market penetration",
            "Competitive advantage",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "SaaS",
            "Digital products",
            "Apps",
            "Content platforms",
        ],
        prerequisites=[
            "Product-market fit",
            "Usage tracking",
            "Billing infrastructure",
        ],
        complementary_frameworks=[
            "product_led_growth",
            "pricing_strategy",
        ],
        time_to_implement="2-3 months",
        resources_required=[
            "Product team",
            "Pricing analysis",
            "A/B testing tools",
        ],
    ),

    "t2d3_growth": Framework(
        id="t2d3_growth",
        name="T2D3 Growth Model",
        description="Framework for achieving hypergrowth: Triple, Triple, Double, Double, Double annual revenue",
        category=FrameworkCategory.GROWTH,
        subcategory="Hypergrowth Strategy",
        when_to_use=[
            "VC-backed startups",
            "Aggressive growth targets",
            "Scale-up planning",
            "Fundraising strategy",
            "Market domination",
        ],
        key_components=[
            "Product-market fit baseline",
            "Sales efficiency",
            "Market expansion",
            "Operational scaling",
            "Capital efficiency",
            "Team scaling",
        ],
        application_steps=[
            "Validate product-market fit",
            "Build repeatable sales process",
            "Achieve first triple (T1)",
            "Scale operations for T2",
            "Expand market reach",
            "Optimize for efficiency (D1-D3)",
            "Maintain growth momentum",
        ],
        expected_outcomes=[
            "Hypergrowth achievement",
            "Market leadership",
            "Valuation increases",
            "Category creation",
            "IPO readiness",
        ],
        complexity=ComplexityLevel.EXPERT,
        industry_relevance=[
            "SaaS",
            "Venture-backed startups",
            "Tech companies",
        ],
        prerequisites=[
            "Strong PMF",
            "Scalable model",
            "Access to capital",
        ],
        complementary_frameworks=[
            "saas_metrics",
            "burn_rate_runway",
        ],
        time_to_implement="5 years",
        resources_required=[
            "Leadership team",
            "Growth capital",
            "Scalable infrastructure",
        ],
    ),

    "dupont_analysis": Framework(
        id="dupont_analysis",
        name="DuPont Analysis",
        description="Framework decomposing ROE into profitability, efficiency, and leverage components",
        category=FrameworkCategory.FINANCIAL,
        subcategory="Financial Analysis",
        when_to_use=[
            "Performance analysis",
            "ROE decomposition",
            "Operational improvement",
            "Peer comparison",
            "Investment analysis",
        ],
        key_components=[
            "Net profit margin",
            "Asset turnover",
            "Financial leverage",
            "ROE decomposition",
            "Extended 5-factor model",
        ],
        application_steps=[
            "Calculate ROE",
            "Decompose into three components",
            "Analyze each component trend",
            "Compare to peers",
            "Identify improvement areas",
            "Develop action plans",
            "Monitor progress",
        ],
        expected_outcomes=[
            "ROE drivers identified",
            "Performance insights",
            "Improvement priorities",
            "Peer positioning",
            "Strategic focus areas",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Financial statements",
            "Historical data",
            "Peer data",
        ],
        complementary_frameworks=[
            "financial_ratios",
            "value_driver_tree",
        ],
        time_to_implement="1 week",
        resources_required=[
            "Financial data",
            "Analysis tools",
            "Finance team",
        ],
    ),

    "working_capital_optimization": Framework(
        id="working_capital_optimization",
        name="Working Capital Optimization",
        description="Framework for improving cash flow by optimizing receivables, inventory, and payables",
        category=FrameworkCategory.FINANCIAL,
        subcategory="Cash Management",
        when_to_use=[
            "Cash flow improvement",
            "Operational efficiency",
            "Liquidity management",
            "Growth funding",
            "Financial health",
        ],
        key_components=[
            "Days Sales Outstanding (DSO)",
            "Days Inventory Outstanding (DIO)",
            "Days Payables Outstanding (DPO)",
            "Cash Conversion Cycle",
            "Working capital targets",
        ],
        application_steps=[
            "Calculate current metrics",
            "Benchmark against industry",
            "Identify improvement opportunities",
            "Set optimization targets",
            "Implement process changes",
            "Monitor progress",
            "Continuous improvement",
        ],
        expected_outcomes=[
            "Improved cash flow",
            "Reduced capital needs",
            "Better liquidity",
            "Operational efficiency",
            "Financial flexibility",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "Manufacturing",
            "Retail",
            "Distribution",
        ],
        prerequisites=[
            "Financial data",
            "Process visibility",
            "Cross-functional support",
        ],
        complementary_frameworks=[
            "supply_chain_finance",
            "lean_operations",
        ],
        time_to_implement="3-6 months",
        resources_required=[
            "Finance team",
            "Operations team",
            "Working capital tools",
        ],
    ),

    "zero_based_budgeting": Framework(
        id="zero_based_budgeting",
        name="Zero-Based Budgeting (ZBB)",
        description="Budgeting approach starting from zero and justifying every expense",
        category=FrameworkCategory.FINANCIAL,
        subcategory="Budget Management",
        when_to_use=[
            "Cost reduction initiatives",
            "Budget reset",
            "Organizational transformation",
            "Efficiency drives",
            "Resource reallocation",
        ],
        key_components=[
            "Decision units",
            "Decision packages",
            "Ranking process",
            "Cost-benefit analysis",
            "Performance measures",
            "Continuous monitoring",
        ],
        application_steps=[
            "Define decision units",
            "Develop decision packages",
            "Evaluate and rank packages",
            "Allocate resources",
            "Implement new budgets",
            "Monitor performance",
            "Adjust as needed",
        ],
        expected_outcomes=[
            "Cost optimization",
            "Resource efficiency",
            "Strategic alignment",
            "Transparency increase",
            "Performance improvement",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Executive commitment",
            "Process documentation",
            "Change management",
        ],
        complementary_frameworks=[
            "activity_based_costing",
            "value_engineering",
        ],
        time_to_implement="4-6 months",
        resources_required=[
            "Finance team",
            "Department heads",
            "ZBB tools",
        ],
    ),

    "economic_value_added": Framework(
        id="economic_value_added",
        name="Economic Value Added (EVA)",
        description="Financial performance measure calculating value created above cost of capital",
        category=FrameworkCategory.FINANCIAL,
        subcategory="Value Management",
        when_to_use=[
            "Performance measurement",
            "Value creation focus",
            "Incentive design",
            "Capital allocation",
            "Shareholder value",
        ],
        key_components=[
            "Net Operating Profit After Tax (NOPAT)",
            "Invested capital",
            "Weighted Average Cost of Capital (WACC)",
            "EVA calculation",
            "Value drivers",
        ],
        application_steps=[
            "Calculate NOPAT",
            "Determine invested capital",
            "Calculate WACC",
            "Compute EVA",
            "Identify value drivers",
            "Set improvement targets",
            "Link to incentives",
        ],
        expected_outcomes=[
            "Value creation focus",
            "Better capital allocation",
            "Aligned incentives",
            "Performance improvement",
            "Shareholder value",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Financial data",
            "Cost of capital",
            "Accounting adjustments",
        ],
        complementary_frameworks=[
            "balanced_scorecard",
            "value_based_management",
        ],
        time_to_implement="2-3 months",
        resources_required=[
            "Finance team",
            "Financial systems",
            "Training",
        ],
    ),

    "revenue_recognition": Framework(
        id="revenue_recognition",
        name="Revenue Recognition Framework (ASC 606/IFRS 15)",
        description="Framework for recognizing revenue from contracts with customers",
        category=FrameworkCategory.FINANCIAL,
        subcategory="Accounting Compliance",
        when_to_use=[
            "Revenue accounting",
            "Contract structuring",
            "Financial reporting",
            "Audit compliance",
            "System implementation",
        ],
        key_components=[
            "Identify contracts",
            "Identify performance obligations",
            "Determine transaction price",
            "Allocate price to obligations",
            "Recognize revenue when satisfied",
        ],
        application_steps=[
            "Review customer contracts",
            "Identify performance obligations",
            "Determine transaction prices",
            "Allocate prices appropriately",
            "Establish satisfaction patterns",
            "Implement tracking systems",
            "Document policies",
        ],
        expected_outcomes=[
            "Compliance achieved",
            "Accurate reporting",
            "Audit readiness",
            "System alignment",
            "Stakeholder confidence",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "All industries",
            "Especially SaaS, Construction",
        ],
        prerequisites=[
            "Contract database",
            "Financial systems",
            "Accounting expertise",
        ],
        complementary_frameworks=[
            "saas_metrics",
            "financial_reporting",
        ],
        time_to_implement="3-6 months",
        resources_required=[
            "Accounting team",
            "Systems upgrade",
            "External advisors",
        ],
    ),

    "theory_of_constraints": Framework(
        id="theory_of_constraints",
        name="Theory of Constraints (TOC)",
        description="Management paradigm focusing on identifying and managing the constraint limiting goal achievement",
        category=FrameworkCategory.OPERATIONS,
        subcategory="Process Optimization",
        when_to_use=[
            "Bottleneck elimination",
            "Throughput improvement",
            "Process optimization",
            "Supply chain issues",
            "Performance improvement",
        ],
        key_components=[
            "Constraint identification",
            "Five focusing steps",
            "Throughput accounting",
            "Buffer management",
            "Drum-Buffer-Rope",
            "Continuous improvement",
        ],
        application_steps=[
            "Identify the system constraint",
            "Exploit the constraint",
            "Subordinate to the constraint",
            "Elevate the constraint",
            "Repeat if constraint shifts",
            "Implement buffer management",
            "Monitor throughput",
        ],
        expected_outcomes=[
            "Increased throughput",
            "Reduced inventory",
            "Improved flow",
            "Higher profitability",
            "System optimization",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "Manufacturing",
            "Services",
            "Software development",
        ],
        prerequisites=[
            "Process visibility",
            "Performance metrics",
            "Change authority",
        ],
        complementary_frameworks=[
            "lean_methodology",
            "six_sigma",
        ],
        time_to_implement="2-4 months",
        resources_required=[
            "TOC expert",
            "Process team",
            "Measurement systems",
        ],
    ),

    "kaizen": Framework(
        id="kaizen",
        name="Kaizen (Continuous Improvement)",
        description="Philosophy of continuous incremental improvements involving all employees",
        category=FrameworkCategory.OPERATIONS,
        subcategory="Continuous Improvement",
        when_to_use=[
            "Culture building",
            "Quality improvement",
            "Cost reduction",
            "Employee engagement",
            "Process refinement",
        ],
        key_components=[
            "PDCA cycle",
            "Gemba walks",
            "Suggestion systems",
            "Quality circles",
            "5S methodology",
            "Standard work",
        ],
        application_steps=[
            "Build improvement culture",
            "Train all employees",
            "Establish suggestion system",
            "Form improvement teams",
            "Implement PDCA cycles",
            "Standardize improvements",
            "Celebrate successes",
        ],
        expected_outcomes=[
            "Continuous improvements",
            "Employee engagement",
            "Quality enhancement",
            "Cost reductions",
            "Cultural transformation",
        ],
        complexity=ComplexityLevel.BASIC,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Management commitment",
            "Employee involvement",
            "Long-term view",
        ],
        complementary_frameworks=[
            "lean_methodology",
            "total_quality_management",
        ],
        time_to_implement="Ongoing",
        resources_required=[
            "Training programs",
            "Improvement tracking",
            "Recognition system",
        ],
    ),

    "business_process_reengineering": Framework(
        id="business_process_reengineering",
        name="Business Process Reengineering (BPR)",
        description="Radical redesign of business processes to achieve dramatic improvements",
        category=FrameworkCategory.OPERATIONS,
        subcategory="Process Transformation",
        when_to_use=[
            "Major performance gaps",
            "Digital transformation",
            "Competitive pressure",
            "Cost crisis",
            "Customer satisfaction issues",
        ],
        key_components=[
            "Process identification",
            "AS-IS analysis",
            "TO-BE design",
            "Gap analysis",
            "Implementation planning",
            "Change management",
        ],
        application_steps=[
            "Define scope and objectives",
            "Map current processes",
            "Analyze performance gaps",
            "Redesign processes radically",
            "Plan implementation",
            "Execute transformation",
            "Monitor and adjust",
        ],
        expected_outcomes=[
            "Dramatic improvements",
            "Cost reductions",
            "Cycle time reduction",
            "Quality improvements",
            "Competitive advantage",
        ],
        complexity=ComplexityLevel.EXPERT,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Executive sponsorship",
            "Change readiness",
            "Resources",
        ],
        complementary_frameworks=[
            "change_management",
            "digital_transformation",
        ],
        time_to_implement="6-12 months",
        resources_required=[
            "BPR team",
            "IT resources",
            "Change management",
        ],
    ),

    "value_stream_mapping": Framework(
        id="value_stream_mapping",
        name="Value Stream Mapping",
        description="Visual tool for analyzing and improving the flow of materials and information",
        category=FrameworkCategory.OPERATIONS,
        subcategory="Process Analysis",
        when_to_use=[
            "Process improvement",
            "Waste identification",
            "Lead time reduction",
            "Flow optimization",
            "Lean implementation",
        ],
        key_components=[
            "Current state map",
            "Future state map",
            "Material flow",
            "Information flow",
            "Timeline",
            "Improvement opportunities",
        ],
        application_steps=[
            "Select value stream",
            "Map current state",
            "Calculate metrics",
            "Identify waste",
            "Design future state",
            "Create implementation plan",
            "Execute improvements",
        ],
        expected_outcomes=[
            "Waste elimination",
            "Lead time reduction",
            "Improved flow",
            "Better visibility",
            "Cost savings",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "Manufacturing",
            "Healthcare",
            "Services",
        ],
        prerequisites=[
            "Process knowledge",
            "Cross-functional team",
            "Lean understanding",
        ],
        complementary_frameworks=[
            "lean_methodology",
            "theory_of_constraints",
        ],
        time_to_implement="2-4 weeks",
        resources_required=[
            "VSM facilitator",
            "Process team",
            "Mapping tools",
        ],
    ),

    "kanban_method": Framework(
        id="kanban_method",
        name="Kanban Method",
        description="Visual system for managing work as it moves through a process",
        category=FrameworkCategory.OPERATIONS,
        subcategory="Workflow Management",
        when_to_use=[
            "Workflow optimization",
            "Work in progress limits",
            "Visual management",
            "Continuous delivery",
            "Team productivity",
        ],
        key_components=[
            "Kanban board",
            "WIP limits",
            "Pull system",
            "Flow metrics",
            "Continuous improvement",
            "Visual signals",
        ],
        application_steps=[
            "Visualize workflow",
            "Set WIP limits",
            "Manage flow",
            "Make policies explicit",
            "Implement feedback loops",
            "Improve collaboratively",
            "Evolve experimentally",
        ],
        expected_outcomes=[
            "Improved flow",
            "Reduced cycle time",
            "Better predictability",
            "Higher quality",
            "Team empowerment",
        ],
        complexity=ComplexityLevel.BASIC,
        industry_relevance=[
            "Software",
            "Manufacturing",
            "Services",
            "Healthcare",
        ],
        prerequisites=[
            "Team commitment",
            "Visual board",
            "Metrics tracking",
        ],
        complementary_frameworks=[
            "agile_methodology",
            "lean_methodology",
        ],
        time_to_implement="1-2 weeks",
        resources_required=[
            "Kanban board",
            "Team training",
            "Metrics tools",
        ],
    ),

    "account_based_marketing": Framework(
        id="account_based_marketing",
        name="Account-Based Marketing (ABM)",
        description="Strategic approach treating individual accounts as markets of one",
        category=FrameworkCategory.MARKETING,
        subcategory="B2B Marketing",
        when_to_use=[
            "B2B enterprise sales",
            "High-value accounts",
            "Long sales cycles",
            "Strategic accounts",
            "Personalized marketing",
        ],
        key_components=[
            "Target account selection",
            "Account insights",
            "Personalized content",
            "Multi-channel orchestration",
            "Sales-marketing alignment",
            "Account engagement scoring",
        ],
        application_steps=[
            "Identify target accounts",
            "Research account needs",
            "Develop account strategies",
            "Create personalized content",
            "Execute multi-channel campaigns",
            "Measure engagement",
            "Optimize approach",
        ],
        expected_outcomes=[
            "Higher conversion rates",
            "Larger deal sizes",
            "Stronger relationships",
            "Marketing-sales alignment",
            "ROI improvement",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "B2B",
            "Enterprise software",
            "Professional services",
        ],
        prerequisites=[
            "CRM system",
            "Account data",
            "Sales alignment",
        ],
        complementary_frameworks=[
            "land_and_expand",
            "solution_selling",
        ],
        time_to_implement="3-6 months",
        resources_required=[
            "ABM platform",
            "Content team",
            "Sales collaboration",
        ],
    ),

    "inbound_marketing": Framework(
        id="inbound_marketing",
        name="Inbound Marketing",
        description="Marketing methodology attracting customers through valuable content and experiences",
        category=FrameworkCategory.MARKETING,
        subcategory="Digital Marketing",
        when_to_use=[
            "Lead generation",
            "Brand building",
            "Content marketing",
            "Cost-effective marketing",
            "Long-term growth",
        ],
        key_components=[
            "Attract (content, SEO)",
            "Convert (forms, CTAs)",
            "Close (email, CRM)",
            "Delight (surveys, content)",
            "Flywheel model",
            "Buyer personas",
        ],
        application_steps=[
            "Define buyer personas",
            "Create content strategy",
            "Optimize for search",
            "Build conversion paths",
            "Nurture leads",
            "Enable sales team",
            "Measure and optimize",
        ],
        expected_outcomes=[
            "Qualified lead generation",
            "Lower acquisition costs",
            "Brand authority",
            "Customer loyalty",
            "Sustainable growth",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "B2B",
            "SaaS",
            "Professional services",
            "E-commerce",
        ],
        prerequisites=[
            "Content capability",
            "Marketing automation",
            "Analytics",
        ],
        complementary_frameworks=[
            "content_marketing_framework",
            "marketing_automation",
        ],
        time_to_implement="3-6 months",
        resources_required=[
            "Content team",
            "Marketing platform",
            "SEO tools",
        ],
    ),

    "marketing_automation": Framework(
        id="marketing_automation",
        name="Marketing Automation Framework",
        description="System for automating repetitive marketing tasks and personalizing customer journeys",
        category=FrameworkCategory.MARKETING,
        subcategory="Marketing Technology",
        when_to_use=[
            "Scale marketing efforts",
            "Lead nurturing",
            "Personalization at scale",
            "Multi-channel campaigns",
            "Marketing efficiency",
        ],
        key_components=[
            "Lead scoring",
            "Email automation",
            "Workflow design",
            "Behavioral triggers",
            "Segmentation",
            "Analytics and reporting",
        ],
        application_steps=[
            "Map customer journeys",
            "Define automation goals",
            "Set up lead scoring",
            "Create email workflows",
            "Design trigger campaigns",
            "Implement personalization",
            "Monitor and optimize",
        ],
        expected_outcomes=[
            "Improved efficiency",
            "Better lead quality",
            "Higher conversion rates",
            "Personalized experiences",
            "Marketing ROI",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "B2B",
            "E-commerce",
            "SaaS",
            "Digital businesses",
        ],
        prerequisites=[
            "Marketing platform",
            "Customer data",
            "Content library",
        ],
        complementary_frameworks=[
            "customer_journey_mapping",
            "lead_scoring",
        ],
        time_to_implement="2-4 months",
        resources_required=[
            "Automation platform",
            "Technical expertise",
            "Content",
        ],
    ),

    "influencer_marketing": Framework(
        id="influencer_marketing",
        name="Influencer Marketing Framework",
        description="Strategic approach to partnering with influencers to reach target audiences",
        category=FrameworkCategory.MARKETING,
        subcategory="Social Media Marketing",
        when_to_use=[
            "Brand awareness",
            "Product launches",
            "Audience expansion",
            "Content creation",
            "Social proof",
        ],
        key_components=[
            "Influencer identification",
            "Audience alignment",
            "Campaign objectives",
            "Content collaboration",
            "Performance metrics",
            "Compliance and disclosure",
        ],
        application_steps=[
            "Define campaign goals",
            "Identify relevant influencers",
            "Analyze audience fit",
            "Develop partnership terms",
            "Create content guidelines",
            "Execute campaigns",
            "Measure impact",
        ],
        expected_outcomes=[
            "Expanded reach",
            "Authentic engagement",
            "Brand awareness",
            "Content creation",
            "Sales impact",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "Consumer goods",
            "Fashion",
            "Beauty",
            "Technology",
        ],
        prerequisites=[
            "Social media presence",
            "Campaign budget",
            "Legal framework",
        ],
        complementary_frameworks=[
            "social_media_strategy",
            "content_marketing_framework",
        ],
        time_to_implement="1-3 months",
        resources_required=[
            "Influencer platform",
            "Campaign manager",
            "Content guidelines",
        ],
    ),

    "attribution_modeling": Framework(
        id="attribution_modeling",
        name="Attribution Modeling Framework",
        description="Framework for assigning credit to marketing touchpoints in the customer journey",
        category=FrameworkCategory.MARKETING,
        subcategory="Marketing Analytics",
        when_to_use=[
            "Marketing ROI analysis",
            "Budget allocation",
            "Channel optimization",
            "Campaign effectiveness",
            "Customer journey analysis",
        ],
        key_components=[
            "First-touch attribution",
            "Last-touch attribution",
            "Linear attribution",
            "Time-decay attribution",
            "Data-driven attribution",
            "Multi-touch models",
        ],
        application_steps=[
            "Map customer touchpoints",
            "Collect interaction data",
            "Choose attribution model",
            "Implement tracking",
            "Analyze channel contribution",
            "Optimize budget allocation",
            "Refine model over time",
        ],
        expected_outcomes=[
            "Channel ROI clarity",
            "Better budget allocation",
            "Campaign optimization",
            "Journey understanding",
            "Performance improvement",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "E-commerce",
            "Digital businesses",
            "Multi-channel retailers",
        ],
        prerequisites=[
            "Tracking infrastructure",
            "Data integration",
            "Analytics expertise",
        ],
        complementary_frameworks=[
            "customer_journey_mapping",
            "marketing_mix_modeling",
        ],
        time_to_implement="2-3 months",
        resources_required=[
            "Attribution platform",
            "Data analyst",
            "Marketing technology",
        ],
    ),

    "user_story_mapping": Framework(
        id="user_story_mapping",
        name="User Story Mapping",
        description="Visual exercise for organizing user stories into a useful model for product planning",
        category=FrameworkCategory.PRODUCT,
        subcategory="Product Planning",
        when_to_use=[
            "Product roadmapping",
            "Release planning",
            "Feature prioritization",
            "Team alignment",
            "MVP definition",
        ],
        key_components=[
            "User activities",
            "User tasks",
            "User stories",
            "Backbone and skeleton",
            "Release slices",
            "Walking skeleton",
        ],
        application_steps=[
            "Identify user activities",
            "Break down into tasks",
            "Write user stories",
            "Arrange horizontally by journey",
            "Prioritize vertically",
            "Define release slices",
            "Plan iterations",
        ],
        expected_outcomes=[
            "Shared understanding",
            "Prioritized backlog",
            "Release plan",
            "MVP clarity",
            "Team alignment",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "Software",
            "Digital products",
            "Agile teams",
        ],
        prerequisites=[
            "User research",
            "Product vision",
            "Cross-functional team",
        ],
        complementary_frameworks=[
            "agile_methodology",
            "mvp_framework",
        ],
        time_to_implement="1-2 days workshop",
        resources_required=[
            "Product team",
            "Facilitator",
            "Wall space or digital tool",
        ],
    ),

    "double_diamond": Framework(
        id="double_diamond",
        name="Double Diamond Design Process",
        description="Design process framework with divergent and convergent thinking in problem and solution spaces",
        category=FrameworkCategory.PRODUCT,
        subcategory="Design Process",
        when_to_use=[
            "Product design",
            "Service design",
            "Problem solving",
            "Innovation projects",
            "UX design",
        ],
        key_components=[
            "Discover (divergent problem space)",
            "Define (convergent problem space)",
            "Develop (divergent solution space)",
            "Deliver (convergent solution space)",
        ],
        application_steps=[
            "Discover: Research and explore",
            "Define: Synthesize and frame problem",
            "Develop: Ideate and prototype",
            "Deliver: Test and implement",
            "Iterate between phases",
            "Document insights",
            "Measure outcomes",
        ],
        expected_outcomes=[
            "Well-defined problems",
            "Innovative solutions",
            "User-centered design",
            "Reduced project risk",
            "Better outcomes",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "Design",
            "Product development",
            "Services",
            "Innovation",
        ],
        prerequisites=[
            "Design skills",
            "Research capability",
            "Prototyping resources",
        ],
        complementary_frameworks=[
            "design_thinking",
            "lean_ux",
        ],
        time_to_implement="4-12 weeks",
        resources_required=[
            "Design team",
            "Research tools",
            "Prototyping materials",
        ],
    ),

    "hook_model": Framework(
        id="hook_model",
        name="Hook Model",
        description="Framework for building habit-forming products through trigger-action-reward-investment cycles",
        category=FrameworkCategory.PRODUCT,
        subcategory="Behavioral Design",
        when_to_use=[
            "Consumer product design",
            "Engagement optimization",
            "Retention improvement",
            "Habit formation",
            "Product stickiness",
        ],
        key_components=[
            "Trigger (external/internal)",
            "Action (simplest behavior)",
            "Variable Reward",
            "Investment (user contribution)",
            "Habit formation",
        ],
        application_steps=[
            "Identify internal triggers",
            "Design external triggers",
            "Simplify key actions",
            "Create variable rewards",
            "Build investment mechanisms",
            "Test habit formation",
            "Iterate and optimize",
        ],
        expected_outcomes=[
            "Increased engagement",
            "Habit formation",
            "Higher retention",
            "Reduced CAC",
            "Product-market fit",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "Consumer apps",
            "Social media",
            "Gaming",
            "E-commerce",
        ],
        prerequisites=[
            "User behavior data",
            "Product flexibility",
            "Ethical considerations",
        ],
        complementary_frameworks=[
            "behavioral_design",
            "gamification",
        ],
        time_to_implement="2-3 months",
        resources_required=[
            "Product team",
            "Behavioral designer",
            "Analytics",
        ],
    ),

    "north_star_metric": Framework(
        id="north_star_metric",
        name="North Star Metric Framework",
        description="Framework for identifying and optimizing the single metric that best captures product value",
        category=FrameworkCategory.PRODUCT,
        subcategory="Product Metrics",
        when_to_use=[
            "Product focus",
            "Team alignment",
            "Growth optimization",
            "Success measurement",
            "Strategic clarity",
        ],
        key_components=[
            "Value identification",
            "Metric selection",
            "Input metrics",
            "Team alignment",
            "Measurement system",
            "Optimization loops",
        ],
        application_steps=[
            "Define product value",
            "Identify candidate metrics",
            "Test metric validity",
            "Select North Star",
            "Define input metrics",
            "Align teams around metric",
            "Build optimization culture",
        ],
        expected_outcomes=[
            "Clear focus",
            "Team alignment",
            "Faster decisions",
            "Growth acceleration",
            "Value optimization",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "Digital products",
            "SaaS",
            "Marketplaces",
            "Apps",
        ],
        prerequisites=[
            "Analytics infrastructure",
            "Product maturity",
            "Leadership buy-in",
        ],
        complementary_frameworks=[
            "aarrr_metrics",
            "okr_framework",
        ],
        time_to_implement="2-4 weeks",
        resources_required=[
            "Product team",
            "Analytics",
            "Leadership alignment",
        ],
    ),

    "feature_flags": Framework(
        id="feature_flags",
        name="Feature Flags Framework",
        description="System for controlling feature releases and enabling experimentation in production",
        category=FrameworkCategory.PRODUCT,
        subcategory="Release Management",
        when_to_use=[
            "Progressive rollouts",
            "A/B testing",
            "Risk mitigation",
            "Feature management",
            "Continuous deployment",
        ],
        key_components=[
            "Flag types",
            "Targeting rules",
            "Rollout strategies",
            "Monitoring system",
            "Flag lifecycle",
            "Technical debt management",
        ],
        application_steps=[
            "Define flag strategy",
            "Implement flag system",
            "Create flag governance",
            "Design rollout plans",
            "Monitor feature performance",
            "Clean up old flags",
            "Document best practices",
        ],
        expected_outcomes=[
            "Safer releases",
            "Faster iteration",
            "Better experimentation",
            "Reduced risk",
            "Feature control",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "Software",
            "SaaS",
            "Digital products",
            "Tech companies",
        ],
        prerequisites=[
            "Technical infrastructure",
            "Monitoring tools",
            "DevOps culture",
        ],
        complementary_frameworks=[
            "continuous_deployment",
            "a_b_testing",
        ],
        time_to_implement="1-2 months",
        resources_required=[
            "Engineering team",
            "Feature flag platform",
            "Monitoring tools",
        ],
    ),

    "authentic_leadership": Framework(
        id="authentic_leadership",
        name="Authentic Leadership",
        description="Leadership approach emphasizing self-awareness, transparency, and genuine relationships",
        category=FrameworkCategory.LEADERSHIP,
        subcategory="Leadership Style",
        when_to_use=[
            "Trust building",
            "Ethical leadership",
            "Culture development",
            "Leadership development",
            "Crisis leadership",
        ],
        key_components=[
            "Self-awareness",
            "Relational transparency",
            "Balanced processing",
            "Moral perspective",
            "Positive psychological capital",
        ],
        application_steps=[
            "Develop self-awareness",
            "Clarify personal values",
            "Practice transparency",
            "Build genuine relationships",
            "Make ethical decisions",
            "Foster positive climate",
            "Lead by example",
        ],
        expected_outcomes=[
            "Higher trust levels",
            "Ethical culture",
            "Employee engagement",
            "Leadership credibility",
            "Organizational resilience",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Self-reflection",
            "Emotional intelligence",
            "Values clarity",
        ],
        complementary_frameworks=[
            "emotional_intelligence",
            "servant_leadership",
        ],
        time_to_implement="Ongoing development",
        resources_required=[
            "Leadership coaching",
            "360 feedback",
            "Self-assessment tools",
        ],
    ),

    "adaptive_leadership": Framework(
        id="adaptive_leadership",
        name="Adaptive Leadership",
        description="Framework for leading through change by mobilizing people to tackle tough challenges",
        category=FrameworkCategory.LEADERSHIP,
        subcategory="Change Leadership",
        when_to_use=[
            "Complex challenges",
            "Organizational change",
            "Crisis management",
            "Innovation needs",
            "Cultural shifts",
        ],
        key_components=[
            "Technical vs adaptive challenges",
            "Get on the balcony",
            "Identify adaptive challenge",
            "Regulate distress",
            "Maintain disciplined attention",
            "Give work back",
        ],
        application_steps=[
            "Diagnose the situation",
            "Distinguish technical from adaptive",
            "Create holding environment",
            "Challenge current approaches",
            "Regulate distress levels",
            "Empower others to adapt",
            "Protect voices of dissent",
        ],
        expected_outcomes=[
            "Successful adaptation",
            "Innovation emergence",
            "Organizational learning",
            "Resilience building",
            "Sustainable change",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Leadership experience",
            "Change mandate",
            "Organizational support",
        ],
        complementary_frameworks=[
            "change_management",
            "transformational_leadership",
        ],
        time_to_implement="6-12 months",
        resources_required=[
            "Leadership development",
            "Coaching support",
            "Safe spaces",
        ],
    ),

    "coaching_leadership": Framework(
        id="coaching_leadership",
        name="Coaching Leadership Style",
        description="Leadership approach focused on developing people through guidance and feedback",
        category=FrameworkCategory.LEADERSHIP,
        subcategory="Leadership Development",
        when_to_use=[
            "Talent development",
            "Performance improvement",
            "Succession planning",
            "Skill building",
            "Employee growth",
        ],
        key_components=[
            "Active listening",
            "Powerful questions",
            "Goal setting",
            "Feedback delivery",
            "Development planning",
            "Accountability",
        ],
        application_steps=[
            "Build coaching relationships",
            "Assess development needs",
            "Set clear goals",
            "Ask powerful questions",
            "Provide regular feedback",
            "Create development plans",
            "Monitor progress",
        ],
        expected_outcomes=[
            "Improved performance",
            "Skill development",
            "Higher engagement",
            "Succession pipeline",
            "Learning culture",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Coaching skills",
            "Time investment",
            "Trust foundation",
        ],
        complementary_frameworks=[
            "situational_leadership",
            "performance_management",
        ],
        time_to_implement="Ongoing practice",
        resources_required=[
            "Coaching training",
            "Time allocation",
            "Development tools",
        ],
    ),

    "distributed_leadership": Framework(
        id="distributed_leadership",
        name="Distributed Leadership",
        description="Leadership model where leadership is shared across multiple people and levels",
        category=FrameworkCategory.LEADERSHIP,
        subcategory="Organizational Leadership",
        when_to_use=[
            "Flat organizations",
            "Knowledge work",
            "Innovation culture",
            "Agile environments",
            "Complex organizations",
        ],
        key_components=[
            "Shared leadership",
            "Collective responsibility",
            "Emergent leadership",
            "Expertise-based influence",
            "Collaborative decision-making",
        ],
        application_steps=[
            "Define leadership distribution",
            "Identify leadership capabilities",
            "Create leadership opportunities",
            "Foster collaboration",
            "Build decision frameworks",
            "Support emergent leaders",
            "Maintain alignment",
        ],
        expected_outcomes=[
            "Increased agility",
            "Better decisions",
            "Leadership capacity",
            "Innovation increase",
            "Employee empowerment",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "Technology",
            "Knowledge industries",
            "Startups",
        ],
        prerequisites=[
            "Collaborative culture",
            "Trust",
            "Clear boundaries",
        ],
        complementary_frameworks=[
            "self_organizing_teams",
            "holacracy",
        ],
        time_to_implement="6-12 months",
        resources_required=[
            "Culture change",
            "Training programs",
            "Collaboration tools",
        ],
    ),

    "leader_member_exchange": Framework(
        id="leader_member_exchange",
        name="Leader-Member Exchange (LMX) Theory",
        description="Framework focusing on the quality of relationships between leaders and individual team members",
        category=FrameworkCategory.LEADERSHIP,
        subcategory="Relationship Management",
        when_to_use=[
            "Team performance",
            "Relationship building",
            "Engagement improvement",
            "Retention strategies",
            "Leadership effectiveness",
        ],
        key_components=[
            "In-group relationships",
            "Out-group relationships",
            "Relationship quality",
            "Trust and respect",
            "Professional development",
            "Performance outcomes",
        ],
        application_steps=[
            "Assess current relationships",
            "Identify in/out groups",
            "Develop inclusive approach",
            "Build high-quality exchanges",
            "Provide equal opportunities",
            "Monitor relationship quality",
            "Address disparities",
        ],
        expected_outcomes=[
            "Better team performance",
            "Higher satisfaction",
            "Reduced turnover",
            "Improved collaboration",
            "Leadership effectiveness",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Self-awareness",
            "Time investment",
            "Interpersonal skills",
        ],
        complementary_frameworks=[
            "emotional_intelligence",
            "team_effectiveness",
        ],
        time_to_implement="3-6 months",
        resources_required=[
            "Leadership assessment",
            "Coaching",
            "Feedback systems",
        ],
    ),
