
# Additional frameworks added by expansion script

    "strategic_options": Framework(
        id="strategic_options",
        name="Strategic Options Framework",
        description="Framework for generating and evaluating strategic alternatives",
        category=FrameworkCategory.STRATEGY,
        subcategory="Strategic Planning",
        when_to_use=[
            "Strategic planning sessions",
            "Major decision points",
            "Growth planning",
            "Crisis response",
            "Investment decisions",
        ],
        key_components=[
            "Option generation",
            "Evaluation criteria",
            "Risk assessment",
            "Resource requirements",
            "Implementation feasibility",
            "Strategic fit",
        ],
        application_steps=[
            "Define strategic challenge",
            "Generate multiple options",
            "Establish evaluation criteria",
            "Assess each option",
            "Compare options systematically",
            "Select preferred option",
            "Develop implementation plan",
        ],
        expected_outcomes=[
            "Comprehensive options",
            "Informed decisions",
            "Risk awareness",
            "Strategic clarity",
            "Action plan",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "All industries",
        ],
        time_to_implement="2-4 weeks",
        resources_required=[
            "Strategy team",
            "Decision makers",
            "Analysis tools",
        ],
    ),

    "platform_strategy": Framework(
        id="platform_strategy",
        name="Platform Strategy Framework",
        description="Framework for building and managing platform businesses with network effects",
        category=FrameworkCategory.STRATEGY,
        subcategory="Platform Business",
        when_to_use=[
            "Platform business development",
            "Ecosystem creation",
            "Network effect optimization",
            "Multi-sided markets",
            "Digital transformation",
        ],
        key_components=[
            "Platform architecture",
            "Network effects",
            "Governance rules",
            "Monetization model",
            "Ecosystem management",
            "Platform evolution",
        ],
        application_steps=[
            "Design platform architecture",
            "Identify sides of platform",
            "Create value propositions",
            "Design interaction rules",
            "Build network effects",
            "Establish governance",
            "Scale platform",
        ],
        expected_outcomes=[
            "Platform launch",
            "Network growth",
            "Ecosystem value",
            "Competitive moat",
            "Scalable business",
        ],
        complexity=ComplexityLevel.EXPERT,
        industry_relevance=[
            "Technology",
            "Digital businesses",
            "Marketplaces",
        ],
        prerequisites=[
            "Technology infrastructure",
            "Market understanding",
            "Capital",
        ],
        time_to_implement="6-12 months",
        resources_required=[
            "Platform team",
            "Technology",
            "Marketing budget",
        ],
    ),

    "strategic_foresight": Framework(
        id="strategic_foresight",
        name="Strategic Foresight Framework",
        description="Systematic approach to exploring future possibilities and preparing strategic responses",
        category=FrameworkCategory.STRATEGY,
        subcategory="Future Planning",
        when_to_use=[
            "Long-term planning",
            "Disruption preparation",
            "Innovation strategy",
            "Risk management",
            "Investment planning",
        ],
        key_components=[
            "Environmental scanning",
            "Trend analysis",
            "Weak signal detection",
            "Future scenarios",
            "Strategic options",
            "Early warning systems",
        ],
        application_steps=[
            "Scan environment systematically",
            "Identify emerging trends",
            "Detect weak signals",
            "Build future scenarios",
            "Assess strategic implications",
            "Develop response strategies",
            "Create monitoring system",
        ],
        expected_outcomes=[
            "Future preparedness",
            "Early advantage",
            "Risk mitigation",
            "Innovation opportunities",
            "Strategic agility",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Research capability",
            "Long-term thinking",
            "Resources",
        ],
        time_to_implement="3-6 months",
        resources_required=[
            "Foresight team",
            "Research tools",
            "External experts",
        ],
    ),

    "competitive_dynamics": Framework(
        id="competitive_dynamics",
        name="Competitive Dynamics Framework",
        description="Framework for understanding and predicting competitive actions and reactions",
        category=FrameworkCategory.STRATEGY,
        subcategory="Competitive Strategy",
        when_to_use=[
            "Competitive response planning",
            "Market entry decisions",
            "Pricing strategies",
            "Product launches",
            "Competitive intelligence",
        ],
        key_components=[
            "Competitive awareness",
            "Motivation to act",
            "Capability to act",
            "Action-reaction cycles",
            "Competitive repertoire",
            "Multi-point competition",
        ],
        application_steps=[
            "Map competitive landscape",
            "Analyze competitor motivations",
            "Assess competitor capabilities",
            "Predict likely actions",
            "Plan response strategies",
            "Execute and monitor",
            "Adapt dynamically",
        ],
        expected_outcomes=[
            "Competitive advantage",
            "Better predictions",
            "Faster responses",
            "Market position",
            "Strategic flexibility",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "All competitive industries",
        ],
        prerequisites=[
            "Competitive intelligence",
            "Market knowledge",
            "Agility",
        ],
        time_to_implement="Ongoing",
        resources_required=[
            "Competitive intelligence team",
            "Analytics",
            "Decision systems",
        ],
    ),

    "real_options": Framework(
        id="real_options",
        name="Real Options Framework",
        description="Strategic approach treating investments as options to manage uncertainty",
        category=FrameworkCategory.STRATEGY,
        subcategory="Investment Strategy",
        when_to_use=[
            "High uncertainty investments",
            "Innovation projects",
            "Market entry decisions",
            "R&D investments",
            "Strategic flexibility",
        ],
        key_components=[
            "Option to defer",
            "Option to expand",
            "Option to abandon",
            "Option to switch",
            "Option valuation",
            "Decision trees",
        ],
        application_steps=[
            "Identify uncertainties",
            "Structure as options",
            "Value each option",
            "Design decision stages",
            "Build flexibility",
            "Monitor triggers",
            "Exercise options optimally",
        ],
        expected_outcomes=[
            "Investment flexibility",
            "Risk mitigation",
            "Value maximization",
            "Better decisions",
            "Strategic agility",
        ],
        complexity=ComplexityLevel.EXPERT,
        industry_relevance=[
            "Technology",
            "Energy",
            "Pharma",
            "Real estate",
        ],
        prerequisites=[
            "Financial modeling",
            "Risk assessment",
            "Option theory",
        ],
        time_to_implement="2-3 months",
        resources_required=[
            "Finance team",
            "Strategy team",
            "Modeling tools",
        ],
    ),

    "ecosystem_strategy": Framework(
        id="ecosystem_strategy",
        name="Ecosystem Strategy Framework",
        description="Framework for creating and capturing value through business ecosystems",
        category=FrameworkCategory.STRATEGY,
        subcategory="Ecosystem Design",
        when_to_use=[
            "Ecosystem development",
            "Partnership strategies",
            "Platform businesses",
            "Innovation networks",
            "Value co-creation",
        ],
        key_components=[
            "Ecosystem mapping",
            "Value flows",
            "Governance mechanisms",
            "Partner roles",
            "Orchestration capabilities",
            "Ecosystem health",
        ],
        application_steps=[
            "Define ecosystem vision",
            "Map potential partners",
            "Design value architecture",
            "Establish governance",
            "Build orchestration capabilities",
            "Launch and scale",
            "Monitor ecosystem health",
        ],
        expected_outcomes=[
            "Ecosystem creation",
            "Shared value",
            "Innovation acceleration",
            "Market expansion",
            "Competitive advantage",
        ],
        complexity=ComplexityLevel.EXPERT,
        industry_relevance=[
            "Technology",
            "Healthcare",
            "Automotive",
            "Financial services",
        ],
        prerequisites=[
            "Partnership skills",
            "Platform thinking",
            "Long-term vision",
        ],
        time_to_implement="12-18 months",
        resources_required=[
            "Ecosystem team",
            "Partnership tools",
            "Platform infrastructure",
        ],
    ),

    "strategic_agility": Framework(
        id="strategic_agility",
        name="Strategic Agility Framework",
        description="Framework for building organizational capability to rapidly adapt strategy",
        category=FrameworkCategory.STRATEGY,
        subcategory="Adaptive Strategy",
        when_to_use=[
            "Volatile markets",
            "Digital disruption",
            "Fast-changing industries",
            "Crisis management",
            "Innovation acceleration",
        ],
        key_components=[
            "Strategic sensitivity",
            "Leadership unity",
            "Resource fluidity",
            "Fast decision-making",
            "Rapid execution",
            "Learning loops",
        ],
        application_steps=[
            "Build sensing capabilities",
            "Create leadership alignment",
            "Design flexible resources",
            "Accelerate decisions",
            "Enable rapid execution",
            "Establish learning systems",
            "Continuously adapt",
        ],
        expected_outcomes=[
            "Faster adaptation",
            "Market responsiveness",
            "Innovation speed",
            "Resilience",
            "Competitive advantage",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Leadership commitment",
            "Organizational flexibility",
            "Technology",
        ],
        time_to_implement="6-12 months",
        resources_required=[
            "Change team",
            "Technology infrastructure",
            "Training",
        ],
    ),

    "strategic_alliances": Framework(
        id="strategic_alliances",
        name="Strategic Alliances Framework",
        description="Framework for forming and managing strategic partnerships and alliances",
        category=FrameworkCategory.STRATEGY,
        subcategory="Partnership Strategy",
        when_to_use=[
            "Market expansion",
            "Capability access",
            "Risk sharing",
            "Innovation collaboration",
            "Resource optimization",
        ],
        key_components=[
            "Partner selection",
            "Alliance structure",
            "Governance model",
            "Value sharing",
            "Risk management",
            "Exit strategies",
        ],
        application_steps=[
            "Define alliance objectives",
            "Identify potential partners",
            "Evaluate partner fit",
            "Structure alliance terms",
            "Negotiate agreements",
            "Implement governance",
            "Manage and evolve",
        ],
        expected_outcomes=[
            "Successful partnerships",
            "Shared value creation",
            "Risk mitigation",
            "Capability enhancement",
            "Market access",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Clear objectives",
            "Partnership experience",
            "Legal support",
        ],
        time_to_implement="3-6 months",
        resources_required=[
            "Alliance team",
            "Legal resources",
            "Integration capabilities",
        ],
    ),

    "frugal_innovation": Framework(
        id="frugal_innovation",
        name="Frugal Innovation Framework",
        description="Approach to creating affordable, sustainable solutions with minimal resources",
        category=FrameworkCategory.INNOVATION,
        subcategory="Resource-Constrained Innovation",
        when_to_use=[
            "Emerging markets",
            "Cost constraints",
            "Sustainability goals",
            "Resource scarcity",
            "Inclusive innovation",
        ],
        key_components=[
            "Resource optimization",
            "Essential features focus",
            "Local material usage",
            "Simplicity principle",
            "Affordability target",
            "Sustainability integration",
        ],
        application_steps=[
            "Understand user constraints",
            "Strip to essential features",
            "Use local resources",
            "Design for affordability",
            "Test with target users",
            "Iterate for optimization",
            "Scale sustainably",
        ],
        expected_outcomes=[
            "Affordable solutions",
            "Market access",
            "Sustainable innovation",
            "Social impact",
            "New business models",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "Healthcare",
            "Consumer goods",
            "Technology",
            "Energy",
        ],
        prerequisites=[
            "User empathy",
            "Design skills",
            "Local knowledge",
        ],
        time_to_implement="3-6 months",
        resources_required=[
            "Design team",
            "Local partners",
            "Testing facilities",
        ],
    ),

    "innovation_diffusion": Framework(
        id="innovation_diffusion",
        name="Innovation Diffusion Model",
        description="Framework explaining how innovations spread through populations over time",
        category=FrameworkCategory.INNOVATION,
        subcategory="Innovation Adoption",
        when_to_use=[
            "Product launch planning",
            "Market penetration",
            "Adoption strategies",
            "Technology rollout",
            "Change management",
        ],
        key_components=[
            "Innovators (2.5%)",
            "Early Adopters (13.5%)",
            "Early Majority (34%)",
            "Late Majority (34%)",
            "Laggards (16%)",
            "Adoption curve",
        ],
        application_steps=[
            "Identify adopter segments",
            "Target innovators first",
            "Leverage early adopters",
            "Cross the chasm",
            "Reach majority markets",
            "Address laggards",
            "Monitor adoption rates",
        ],
        expected_outcomes=[
            "Adoption strategy",
            "Market penetration",
            "Segment targeting",
            "Communication plan",
            "Growth trajectory",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "Technology",
            "Consumer products",
            "Healthcare",
            "Education",
        ],
        prerequisites=[
            "Market research",
            "Segmentation data",
            "Communication channels",
        ],
        time_to_implement="Ongoing process",
        resources_required=[
            "Marketing team",
            "Research data",
            "Communication budget",
        ],
    ),

    "innovation_portfolio_management": Framework(
        id="innovation_portfolio_management",
        name="Innovation Portfolio Management",
        description="Framework for managing multiple innovation projects as an integrated portfolio",
        category=FrameworkCategory.INNOVATION,
        subcategory="Innovation Management",
        when_to_use=[
            "R&D management",
            "Innovation investment",
            "Resource allocation",
            "Risk balancing",
            "Strategic alignment",
        ],
        key_components=[
            "Portfolio mapping",
            "Risk-return balance",
            "Resource allocation",
            "Stage-gate integration",
            "Performance metrics",
            "Portfolio optimization",
        ],
        application_steps=[
            "Map all innovation projects",
            "Assess risk and return",
            "Evaluate strategic fit",
            "Balance portfolio mix",
            "Allocate resources optimally",
            "Monitor portfolio health",
            "Rebalance regularly",
        ],
        expected_outcomes=[
            "Balanced portfolio",
            "Optimized returns",
            "Risk management",
            "Strategic alignment",
            "Resource efficiency",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "R&D intensive industries",
            "Technology",
            "Pharma",
        ],
        prerequisites=[
            "Portfolio tools",
            "Metrics systems",
            "Governance structure",
        ],
        time_to_implement="2-3 months",
        resources_required=[
            "Portfolio manager",
            "Analytics tools",
            "Review committees",
        ],
    ),

    "co_creation": Framework(
        id="co_creation",
        name="Co-Creation Framework",
        description="Approach to innovation through collaborative value creation with stakeholders",
        category=FrameworkCategory.INNOVATION,
        subcategory="Collaborative Innovation",
        when_to_use=[
            "Customer innovation",
            "Partner collaboration",
            "Community engagement",
            "Service design",
            "Product development",
        ],
        key_components=[
            "Stakeholder engagement",
            "Collaboration platforms",
            "Value sharing models",
            "Co-creation processes",
            "IP management",
            "Community building",
        ],
        application_steps=[
            "Identify co-creation partners",
            "Design engagement model",
            "Create collaboration platform",
            "Facilitate co-creation",
            "Manage IP rights",
            "Share value created",
            "Build ongoing community",
        ],
        expected_outcomes=[
            "User-driven innovation",
            "Stakeholder engagement",
            "Better solutions",
            "Shared ownership",
            "Innovation ecosystem",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "Consumer products",
            "Services",
            "Software",
            "Healthcare",
        ],
        prerequisites=[
            "Collaboration tools",
            "Legal framework",
            "Community management",
        ],
        time_to_implement="3-6 months",
        resources_required=[
            "Community manager",
            "Platform tools",
            "Legal support",
        ],
    ),

    "systematic_inventive_thinking": Framework(
        id="systematic_inventive_thinking",
        name="Systematic Inventive Thinking (SIT)",
        description="Innovation method using five thinking patterns to generate creative solutions",
        category=FrameworkCategory.INNOVATION,
        subcategory="Creative Problem Solving",
        when_to_use=[
            "Product innovation",
            "Problem solving",
            "Creative workshops",
            "Service innovation",
            "Process improvement",
        ],
        key_components=[
            "Subtraction",
            "Division",
            "Multiplication",
            "Task Unification",
            "Attribute Dependency",
            "Function follows form",
        ],
        application_steps=[
            "Define innovation challenge",
            "Apply SIT techniques systematically",
            "Generate solution concepts",
            "Evaluate feasibility",
            "Prototype solutions",
            "Test with users",
            "Refine and implement",
        ],
        expected_outcomes=[
            "Creative solutions",
            "Systematic innovation",
            "Breakthrough ideas",
            "Practical innovations",
            "Problem resolution",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "SIT training",
            "Workshop facilitation",
            "Open mindset",
        ],
        time_to_implement="1-2 weeks per session",
        resources_required=[
            "Trained facilitator",
            "Workshop space",
            "Prototyping materials",
        ],
    ),

    "innovation_metrics": Framework(
        id="innovation_metrics",
        name="Innovation Metrics Framework",
        description="System for measuring and tracking innovation performance and impact",
        category=FrameworkCategory.INNOVATION,
        subcategory="Innovation Measurement",
        when_to_use=[
            "Innovation tracking",
            "Performance management",
            "ROI measurement",
            "Portfolio decisions",
            "Continuous improvement",
        ],
        key_components=[
            "Input metrics",
            "Process metrics",
            "Output metrics",
            "Outcome metrics",
            "Leading indicators",
            "Innovation dashboard",
        ],
        application_steps=[
            "Define innovation goals",
            "Select relevant metrics",
            "Establish baselines",
            "Create measurement system",
            "Track performance",
            "Analyze trends",
            "Drive improvements",
        ],
        expected_outcomes=[
            "Innovation visibility",
            "Performance tracking",
            "ROI demonstration",
            "Decision support",
            "Continuous improvement",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Data systems",
            "Innovation process",
            "Analytics capability",
        ],
        time_to_implement="2-3 months",
        resources_required=[
            "Analytics team",
            "Dashboard tools",
            "Data infrastructure",
        ],
    ),

    "biomimicry_innovation": Framework(
        id="biomimicry_innovation",
        name="Biomimicry Innovation Framework",
        description="Innovation approach that emulates nature's patterns and strategies",
        category=FrameworkCategory.INNOVATION,
        subcategory="Nature-Inspired Innovation",
        when_to_use=[
            "Sustainable design",
            "Complex problem solving",
            "Material innovation",
            "System design",
            "Efficiency optimization",
        ],
        key_components=[
            "Biology to design",
            "Challenge to biology",
            "Nature's principles",
            "Function analysis",
            "Abstraction process",
            "Sustainability criteria",
        ],
        application_steps=[
            "Define design challenge",
            "Explore biological models",
            "Abstract design principles",
            "Apply to challenge",
            "Evaluate sustainability",
            "Prototype and test",
            "Iterate with nature",
        ],
        expected_outcomes=[
            "Sustainable innovations",
            "Novel solutions",
            "Efficiency gains",
            "Reduced environmental impact",
            "Breakthrough designs",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "Architecture",
            "Materials",
            "Energy",
            "Manufacturing",
        ],
        prerequisites=[
            "Biology knowledge",
            "Design expertise",
            "Sustainability focus",
        ],
        time_to_implement="4-8 months",
        resources_required=[
            "Biomimicry experts",
            "Design team",
            "Research resources",
        ],
    ),

    "innovation_culture": Framework(
        id="innovation_culture",
        name="Innovation Culture Framework",
        description="Framework for building and sustaining a culture of innovation",
        category=FrameworkCategory.INNOVATION,
        subcategory="Cultural Innovation",
        when_to_use=[
            "Culture transformation",
            "Innovation capability building",
            "Employee engagement",
            "Organizational change",
            "Performance improvement",
        ],
        key_components=[
            "Innovation values",
            "Leadership behaviors",
            "Psychological safety",
            "Resource allocation",
            "Recognition systems",
            "Innovation processes",
        ],
        application_steps=[
            "Assess current culture",
            "Define innovation values",
            "Align leadership behaviors",
            "Create safe spaces",
            "Allocate resources",
            "Implement recognition",
            "Embed in processes",
        ],
        expected_outcomes=[
            "Innovation mindset",
            "Increased ideas",
            "Better execution",
            "Employee engagement",
            "Sustained innovation",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Leadership commitment",
            "Change readiness",
            "Long-term view",
        ],
        time_to_implement="12-24 months",
        resources_required=[
            "Culture team",
            "Training programs",
            "Communication tools",
        ],
    ),

    "blitzscaling": Framework(
        id="blitzscaling",
        name="Blitzscaling Framework",
        description="Framework for prioritizing speed over efficiency in pursuit of massive scale",
        category=FrameworkCategory.GROWTH,
        subcategory="Hypergrowth",
        when_to_use=[
            "Winner-take-all markets",
            "Network effect businesses",
            "First-mover advantage",
            "Venture-backed startups",
            "Global expansion",
        ],
        key_components=[
            "Speed over efficiency",
            "Embracing chaos",
            "Counterintuitive rules",
            "Scaling stages",
            "Management transitions",
            "Risk tolerance",
        ],
        application_steps=[
            "Identify market opportunity",
            "Secure growth capital",
            "Prioritize speed",
            "Accept inefficiencies",
            "Scale rapidly",
            "Fix problems later",
            "Transition management",
        ],
        expected_outcomes=[
            "Market dominance",
            "Rapid scale",
            "Network effects",
            "Category leadership",
            "Valuation growth",
        ],
        complexity=ComplexityLevel.EXPERT,
        industry_relevance=[
            "Technology",
            "Marketplaces",
            "Platform businesses",
        ],
        prerequisites=[
            "Large market",
            "Capital access",
            "Risk tolerance",
        ],
        time_to_implement="2-5 years",
        resources_required=[
            "Growth capital",
            "Talent pipeline",
            "Infrastructure",
        ],
    ),

    "customer_success": Framework(
        id="customer_success",
        name="Customer Success Framework",
        description="Proactive approach to ensuring customers achieve their desired outcomes",
        category=FrameworkCategory.GROWTH,
        subcategory="Retention Growth",
        when_to_use=[
            "SaaS businesses",
            "Subscription models",
            "B2B growth",
            "Retention improvement",
            "Expansion revenue",
        ],
        key_components=[
            "Customer journey mapping",
            "Success metrics",
            "Health scores",
            "Proactive engagement",
            "Value realization",
            "Expansion playbooks",
        ],
        application_steps=[
            "Define customer success criteria",
            "Map customer journey",
            "Create health scoring",
            "Build engagement model",
            "Implement success plans",
            "Track value delivery",
            "Drive expansion",
        ],
        expected_outcomes=[
            "Higher retention",
            "Expansion revenue",
            "Customer advocacy",
            "Reduced churn",
            "Increased LTV",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "SaaS",
            "B2B services",
            "Subscription businesses",
        ],
        prerequisites=[
            "Customer data",
            "Success team",
            "Engagement tools",
        ],
        time_to_implement="3-6 months",
        resources_required=[
            "CS team",
            "CS platform",
            "Playbooks",
        ],
    ),

    "referral_marketing": Framework(
        id="referral_marketing",
        name="Referral Marketing Framework",
        description="Systematic approach to generating growth through customer referrals",
        category=FrameworkCategory.GROWTH,
        subcategory="Organic Growth",
        when_to_use=[
            "Customer acquisition",
            "Viral growth",
            "Cost-effective marketing",
            "Brand advocacy",
            "Network expansion",
        ],
        key_components=[
            "Referral incentives",
            "Program mechanics",
            "Tracking systems",
            "User experience",
            "Reward structure",
            "Viral loops",
        ],
        application_steps=[
            "Design referral program",
            "Create incentive structure",
            "Build tracking system",
            "Optimize user flow",
            "Launch to segments",
            "Monitor performance",
            "Iterate and scale",
        ],
        expected_outcomes=[
            "Lower CAC",
            "Quality customers",
            "Viral growth",
            "Brand advocates",
            "Sustainable acquisition",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "E-commerce",
            "Apps",
            "Services",
            "Financial services",
        ],
        prerequisites=[
            "Happy customers",
            "Tracking infrastructure",
            "Reward system",
        ],
        time_to_implement="4-8 weeks",
        resources_required=[
            "Marketing team",
            "Referral platform",
            "Analytics",
        ],
    ),

    "growth_team_framework": Framework(
        id="growth_team_framework",
        name="Growth Team Framework",
        description="Structure and process for building high-performing growth teams",
        category=FrameworkCategory.GROWTH,
        subcategory="Growth Organization",
        when_to_use=[
            "Building growth function",
            "Scaling growth efforts",
            "Cross-functional growth",
            "Growth acceleration",
            "Data-driven culture",
        ],
        key_components=[
            "Team structure",
            "Growth process",
            "Experimentation cadence",
            "Metrics ownership",
            "Tool stack",
            "Stakeholder alignment",
        ],
        application_steps=[
            "Define growth charter",
            "Build cross-functional team",
            "Establish growth process",
            "Set experimentation rhythm",
            "Create metrics dashboard",
            "Align with stakeholders",
            "Scale what works",
        ],
        expected_outcomes=[
            "Systematic growth",
            "Faster experimentation",
            "Data-driven decisions",
            "Cross-functional alignment",
            "Sustainable growth engine",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "Digital businesses",
            "SaaS",
            "E-commerce",
            "Apps",
        ],
        prerequisites=[
            "Executive support",
            "Data infrastructure",
            "Growth mindset",
        ],
        time_to_implement="2-3 months",
        resources_required=[
            "Growth lead",
            "Cross-functional team",
            "Tools budget",
        ],
    ),

    "market_development": Framework(
        id="market_development",
        name="Market Development Framework",
        description="Systematic approach to expanding into new markets with existing products",
        category=FrameworkCategory.GROWTH,
        subcategory="Market Expansion",
        when_to_use=[
            "Geographic expansion",
            "New segment entry",
            "International growth",
            "Market saturation",
            "Growth acceleration",
        ],
        key_components=[
            "Market assessment",
            "Entry strategy",
            "Localization needs",
            "Channel strategy",
            "Risk mitigation",
            "Success metrics",
        ],
        application_steps=[
            "Identify target markets",
            "Assess market potential",
            "Analyze entry barriers",
            "Develop entry strategy",
            "Plan localization",
            "Execute market entry",
            "Monitor and adjust",
        ],
        expected_outcomes=[
            "New market access",
            "Revenue diversification",
            "Growth acceleration",
            "Risk distribution",
            "Market leadership",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Market research",
            "Expansion capital",
            "Local expertise",
        ],
        time_to_implement="6-12 months",
        resources_required=[
            "Market entry team",
            "Local partners",
            "Marketing budget",
        ],
    ),

    "retention_marketing": Framework(
        id="retention_marketing",
        name="Retention Marketing Framework",
        description="Comprehensive approach to keeping and growing existing customers",
        category=FrameworkCategory.GROWTH,
        subcategory="Customer Retention",
        when_to_use=[
            "Reducing churn",
            "Increasing LTV",
            "Customer loyalty",
            "Repeat purchases",
            "Engagement improvement",
        ],
        key_components=[
            "Retention metrics",
            "Engagement programs",
            "Loyalty mechanisms",
            "Personalization",
            "Win-back campaigns",
            "Customer feedback loops",
        ],
        application_steps=[
            "Analyze retention metrics",
            "Segment by behavior",
            "Design retention programs",
            "Implement personalization",
            "Create loyalty rewards",
            "Execute win-back campaigns",
            "Measure and optimize",
        ],
        expected_outcomes=[
            "Reduced churn",
            "Higher LTV",
            "Increased loyalty",
            "Better economics",
            "Sustainable growth",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "E-commerce",
            "SaaS",
            "Services",
            "Retail",
        ],
        prerequisites=[
            "Customer data",
            "Marketing automation",
            "Analytics",
        ],
        time_to_implement="2-4 months",
        resources_required=[
            "Retention team",
            "Marketing tools",
            "Analytics platform",
        ],
    ),

    "partnership_growth": Framework(
        id="partnership_growth",
        name="Partnership Growth Framework",
        description="Framework for driving growth through strategic partnerships and channels",
        category=FrameworkCategory.GROWTH,
        subcategory="Partnership Strategy",
        when_to_use=[
            "Channel development",
            "Market expansion",
            "Resource leverage",
            "Ecosystem growth",
            "B2B distribution",
        ],
        key_components=[
            "Partner identification",
            "Value proposition",
            "Partnership models",
            "Enablement programs",
            "Performance tracking",
            "Relationship management",
        ],
        application_steps=[
            "Define partnership strategy",
            "Identify ideal partners",
            "Create partner value prop",
            "Design partnership models",
            "Build enablement programs",
            "Launch partnerships",
            "Manage and optimize",
        ],
        expected_outcomes=[
            "Expanded reach",
            "Leveraged growth",
            "New channels",
            "Ecosystem value",
            "Scalable distribution",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "B2B",
            "Technology",
            "Services",
            "Distribution",
        ],
        prerequisites=[
            "Partner strategy",
            "Support resources",
            "Tracking systems",
        ],
        time_to_implement="3-6 months",
        resources_required=[
            "Partner team",
            "Enablement tools",
            "Support systems",
        ],
    ),

    "community_led_growth": Framework(
        id="community_led_growth",
        name="Community-Led Growth Framework",
        description="Growth strategy leveraging community building and engagement",
        category=FrameworkCategory.GROWTH,
        subcategory="Community Growth",
        when_to_use=[
            "Developer tools",
            "B2B SaaS",
            "Content platforms",
            "Education products",
            "Open source projects",
        ],
        key_components=[
            "Community strategy",
            "Platform selection",
            "Engagement models",
            "Content programs",
            "Ambassador programs",
            "Community metrics",
        ],
        application_steps=[
            "Define community purpose",
            "Choose platforms",
            "Recruit initial members",
            "Create engagement programs",
            "Develop content strategy",
            "Build ambassador program",
            "Scale community",
        ],
        expected_outcomes=[
            "Organic growth",
            "Lower CAC",
            "Product feedback",
            "Brand advocacy",
            "Sustainable moat",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "Technology",
            "SaaS",
            "Developer tools",
            "Education",
        ],
        prerequisites=[
            "Community platform",
            "Content capability",
            "Long-term commitment",
        ],
        time_to_implement="6-12 months",
        resources_required=[
            "Community manager",
            "Platform tools",
            "Content team",
        ],
    ),

    "matrix_organization": Framework(
        id="matrix_organization",
        name="Matrix Organization Structure",
        description="Organizational structure with dual reporting relationships",
        category=FrameworkCategory.ORGANIZATIONAL,
        subcategory="Organizational Structure",
        when_to_use=[
            "Complex projects",
            "Cross-functional needs",
            "Resource optimization",
            "Global organizations",
            "Multiple product lines",
        ],
        key_components=[
            "Dual reporting",
            "Functional managers",
            "Project managers",
            "Resource sharing",
            "Decision rights",
            "Conflict resolution",
        ],
        application_steps=[
            "Define matrix dimensions",
            "Clarify reporting relationships",
            "Establish decision rights",
            "Create collaboration processes",
            "Build conflict resolution",
            "Train managers and employees",
            "Monitor effectiveness",
        ],
        expected_outcomes=[
            "Resource flexibility",
            "Cross-functional collaboration",
            "Skill utilization",
            "Project success",
            "Knowledge sharing",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "Consulting",
            "Technology",
            "Engineering",
            "Pharma",
        ],
        prerequisites=[
            "Collaborative culture",
            "Clear processes",
            "Strong leadership",
        ],
        time_to_implement="6-12 months",
        resources_required=[
            "Change management",
            "Training programs",
            "Communication tools",
        ],
    ),

    "holacracy": Framework(
        id="holacracy",
        name="Holacracy",
        description="Self-management practice distributing authority through defined roles",
        category=FrameworkCategory.ORGANIZATIONAL,
        subcategory="Self-Management",
        when_to_use=[
            "Flat organizations",
            "Startup scaling",
            "Innovation culture",
            "Agile environments",
            "Employee empowerment",
        ],
        key_components=[
            "Roles not jobs",
            "Distributed authority",
            "Tactical meetings",
            "Governance meetings",
            "Tensions processing",
            "Constitutional rules",
        ],
        application_steps=[
            "Adopt holacracy constitution",
            "Define initial roles",
            "Train on processes",
            "Run governance meetings",
            "Process tensions",
            "Evolve role structure",
            "Monitor adoption",
        ],
        expected_outcomes=[
            "Distributed decision-making",
            "Clear accountabilities",
            "Adaptive organization",
            "Employee autonomy",
            "Rapid response",
        ],
        complexity=ComplexityLevel.EXPERT,
        industry_relevance=[
            "Startups",
            "Tech companies",
            "Creative agencies",
        ],
        prerequisites=[
            "Cultural readiness",
            "Training investment",
            "Leadership support",
        ],
        time_to_implement="6-12 months",
        resources_required=[
            "Holacracy coach",
            "Training programs",
            "Software tools",
        ],
    ),

    "organizational_network_analysis": Framework(
        id="organizational_network_analysis",
        name="Organizational Network Analysis (ONA)",
        description="Method for visualizing and analyzing relationships and information flows",
        category=FrameworkCategory.ORGANIZATIONAL,
        subcategory="Organizational Analysis",
        when_to_use=[
            "Organizational design",
            "Change management",
            "Collaboration improvement",
            "Knowledge management",
            "Culture assessment",
        ],
        key_components=[
            "Network mapping",
            "Centrality measures",
            "Information flows",
            "Collaboration patterns",
            "Influence networks",
            "Communication gaps",
        ],
        application_steps=[
            "Define analysis scope",
            "Collect relationship data",
            "Map network structure",
            "Analyze patterns",
            "Identify key nodes",
            "Find collaboration gaps",
            "Design interventions",
        ],
        expected_outcomes=[
            "Collaboration insights",
            "Improved communication",
            "Better org design",
            "Change acceleration",
            "Knowledge flow",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Data collection tools",
            "Analysis software",
            "Privacy protocols",
        ],
        time_to_implement="4-8 weeks",
        resources_required=[
            "ONA specialist",
            "Survey tools",
            "Analytics software",
        ],
    ),

    "organizational_ambidexterity": Framework(
        id="organizational_ambidexterity",
        name="Organizational Ambidexterity",
        description="Framework for balancing exploitation of current capabilities with exploration of new ones",
        category=FrameworkCategory.ORGANIZATIONAL,
        subcategory="Organizational Capability",
        when_to_use=[
            "Innovation balance",
            "Digital transformation",
            "Market disruption",
            "Growth strategy",
            "Capability building",
        ],
        key_components=[
            "Exploitation activities",
            "Exploration activities",
            "Structural separation",
            "Contextual integration",
            "Leadership paradox",
            "Dynamic capabilities",
        ],
        application_steps=[
            "Assess current balance",
            "Define ambidexterity needs",
            "Design organizational approach",
            "Create separate structures",
            "Build integration mechanisms",
            "Develop leadership skills",
            "Monitor balance",
        ],
        expected_outcomes=[
            "Innovation balance",
            "Sustained performance",
            "Future readiness",
            "Competitive advantage",
            "Organizational resilience",
        ],
        complexity=ComplexityLevel.EXPERT,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Leadership capability",
            "Resources",
            "Cultural flexibility",
        ],
        time_to_implement="12-18 months",
        resources_required=[
            "Leadership development",
            "Organizational design",
            "Change management",
        ],
    ),

    "teal_organizations": Framework(
        id="teal_organizations",
        name="Teal Organizations",
        description="Evolutionary organizational model based on self-management, wholeness, and purpose",
        category=FrameworkCategory.ORGANIZATIONAL,
        subcategory="Evolutionary Organizations",
        when_to_use=[
            "Cultural transformation",
            "Purpose-driven organizations",
            "Self-management adoption",
            "Employee empowerment",
            "Organizational evolution",
        ],
        key_components=[
            "Self-management",
            "Wholeness",
            "Evolutionary purpose",
            "Distributed decision-making",
            "Advice process",
            "Conflict resolution",
        ],
        application_steps=[
            "Understand teal principles",
            "Assess organizational readiness",
            "Start with experiments",
            "Implement self-management",
            "Foster wholeness",
            "Clarify evolutionary purpose",
            "Evolve practices",
        ],
        expected_outcomes=[
            "Employee fulfillment",
            "Organizational agility",
            "Innovation increase",
            "Purpose alignment",
            "Sustainable performance",
        ],
        complexity=ComplexityLevel.EXPERT,
        industry_relevance=[
            "Progressive organizations",
            "Social enterprises",
            "Tech companies",
        ],
        prerequisites=[
            "Leadership commitment",
            "Cultural readiness",
            "Long-term view",
        ],
        time_to_implement="2-3 years",
        resources_required=[
            "Cultural transformation team",
            "Training",
            "Coaching support",
        ],
    ),

    "predictive_analytics": Framework(
        id="predictive_analytics",
        name="Predictive Analytics Framework",
        description="Framework for using historical data to predict future outcomes",
        category=FrameworkCategory.ANALYTICS,
        subcategory="Advanced Analytics",
        when_to_use=[
            "Demand forecasting",
            "Risk assessment",
            "Customer behavior prediction",
            "Maintenance planning",
            "Financial modeling",
        ],
        key_components=[
            "Data preparation",
            "Feature engineering",
            "Model selection",
            "Training and validation",
            "Deployment pipeline",
            "Performance monitoring",
        ],
        application_steps=[
            "Define prediction objectives",
            "Collect and prepare data",
            "Engineer relevant features",
            "Select and train models",
            "Validate predictions",
            "Deploy to production",
            "Monitor and retrain",
        ],
        expected_outcomes=[
            "Accurate predictions",
            "Better decisions",
            "Risk mitigation",
            "Operational efficiency",
            "Competitive advantage",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "All data-rich industries",
        ],
        prerequisites=[
            "Data infrastructure",
            "Analytics skills",
            "Domain knowledge",
        ],
        time_to_implement="3-6 months",
        resources_required=[
            "Data scientists",
            "ML platform",
            "Computing resources",
        ],
    ),

    "customer_analytics": Framework(
        id="customer_analytics",
        name="Customer Analytics Framework",
        description="Comprehensive approach to understanding and predicting customer behavior",
        category=FrameworkCategory.ANALYTICS,
        subcategory="Customer Intelligence",
        when_to_use=[
            "Customer segmentation",
            "Churn prediction",
            "Lifetime value modeling",
            "Personalization",
            "Customer experience optimization",
        ],
        key_components=[
            "Customer data integration",
            "Behavioral analytics",
            "Segmentation models",
            "Predictive scoring",
            "Journey analytics",
            "Real-time insights",
        ],
        application_steps=[
            "Integrate customer data sources",
            "Build unified customer view",
            "Analyze behavioral patterns",
            "Create segmentation models",
            "Develop predictive scores",
            "Enable real-time insights",
            "Activate across channels",
        ],
        expected_outcomes=[
            "Customer understanding",
            "Improved targeting",
            "Higher retention",
            "Increased revenue",
            "Better experiences",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "Retail",
            "E-commerce",
            "Financial services",
            "Telecom",
        ],
        prerequisites=[
            "Customer data platform",
            "Analytics tools",
            "Privacy compliance",
        ],
        time_to_implement="4-6 months",
        resources_required=[
            "Analytics team",
            "CDP platform",
            "Integration tools",
        ],
    ),

    "marketing_mix_modeling": Framework(
        id="marketing_mix_modeling",
        name="Marketing Mix Modeling (MMM)",
        description="Statistical analysis technique to measure marketing effectiveness and ROI",
        category=FrameworkCategory.ANALYTICS,
        subcategory="Marketing Analytics",
        when_to_use=[
            "Marketing budget allocation",
            "Channel effectiveness",
            "ROI measurement",
            "Media planning",
            "Performance optimization",
        ],
        key_components=[
            "Data collection",
            "Statistical modeling",
            "Media contribution",
            "Seasonality effects",
            "Competitive factors",
            "Optimization algorithms",
        ],
        application_steps=[
            "Gather historical data",
            "Clean and prepare data",
            "Build statistical models",
            "Decompose sales drivers",
            "Calculate channel ROI",
            "Optimize media mix",
            "Create planning scenarios",
        ],
        expected_outcomes=[
            "Marketing ROI clarity",
            "Optimal budget allocation",
            "Channel insights",
            "Improved efficiency",
            "Data-driven planning",
        ],
        complexity=ComplexityLevel.EXPERT,
        industry_relevance=[
            "CPG",
            "Retail",
            "Automotive",
            "Financial services",
        ],
        prerequisites=[
            "Historical data",
            "Statistical expertise",
            "Clean data sources",
        ],
        time_to_implement="2-3 months",
        resources_required=[
            "Analytics team",
            "Statistical software",
            "Data infrastructure",
        ],
    ),

    "ab_testing_framework": Framework(
        id="ab_testing_framework",
        name="A/B Testing Framework",
        description="Systematic approach to running controlled experiments for optimization",
        category=FrameworkCategory.ANALYTICS,
        subcategory="Experimentation",
        when_to_use=[
            "Website optimization",
            "Feature testing",
            "Marketing optimization",
            "Product decisions",
            "Conversion improvement",
        ],
        key_components=[
            "Hypothesis formation",
            "Sample size calculation",
            "Test design",
            "Statistical significance",
            "Results interpretation",
            "Decision framework",
        ],
        application_steps=[
            "Form clear hypothesis",
            "Calculate sample size",
            "Design test variations",
            "Implement test setup",
            "Run experiment",
            "Analyze results",
            "Make decisions",
        ],
        expected_outcomes=[
            "Data-driven decisions",
            "Conversion improvements",
            "Risk reduction",
            "Continuous optimization",
            "Learning culture",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "E-commerce",
            "SaaS",
            "Digital businesses",
            "Apps",
        ],
        prerequisites=[
            "Testing platform",
            "Traffic volume",
            "Analytics setup",
        ],
        time_to_implement="1-4 weeks per test",
        resources_required=[
            "Testing platform",
            "Analytics tools",
            "Development resources",
        ],
    ),

    "data_governance": Framework(
        id="data_governance",
        name="Data Governance Framework",
        description="Framework for managing data availability, quality, security, and compliance",
        category=FrameworkCategory.ANALYTICS,
        subcategory="Data Management",
        when_to_use=[
            "Data quality issues",
            "Compliance requirements",
            "Data democratization",
            "Risk management",
            "Digital transformation",
        ],
        key_components=[
            "Data ownership",
            "Quality standards",
            "Security protocols",
            "Access controls",
            "Compliance policies",
            "Lifecycle management",
        ],
        application_steps=[
            "Assess current state",
            "Define governance structure",
            "Establish data policies",
            "Implement quality controls",
            "Create security protocols",
            "Build compliance processes",
            "Monitor and enforce",
        ],
        expected_outcomes=[
            "Data quality improvement",
            "Compliance assurance",
            "Risk reduction",
            "Better decision-making",
            "Operational efficiency",
        ],
        complexity=ComplexityLevel.ADVANCED,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Executive sponsorship",
            "Data inventory",
            "Compliance knowledge",
        ],
        time_to_implement="6-12 months",
        resources_required=[
            "Governance team",
            "Data tools",
            "Training programs",
        ],
    ),

    "kotters_8_step": Framework(
        id="kotters_8_step",
        name="Kotter's 8-Step Change Model",
        description="Structured approach to leading organizational change",
        category=FrameworkCategory.CHANGE,
        subcategory="Change Leadership",
        when_to_use=[
            "Major transformations",
            "Cultural change",
            "Strategic shifts",
            "Merger integration",
            "Digital transformation",
        ],
        key_components=[
            "Create urgency",
            "Build coalition",
            "Form vision",
            "Communicate vision",
            "Empower action",
            "Generate wins",
            "Consolidate gains",
            "Anchor changes",
        ],
        application_steps=[
            "Establish sense of urgency",
            "Create guiding coalition",
            "Develop change vision",
            "Communicate vision broadly",
            "Empower broad-based action",
            "Generate short-term wins",
            "Consolidate and produce more",
            "Anchor in corporate culture",
        ],
        expected_outcomes=[
            "Successful transformation",
            "Cultural alignment",
            "Sustained change",
            "Stakeholder buy-in",
            "Organizational agility",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Leadership commitment",
            "Change readiness",
            "Resources",
        ],
        time_to_implement="12-24 months",
        resources_required=[
            "Change team",
            "Communication resources",
            "Training",
        ],
    ),

    "adkar_model": Framework(
        id="adkar_model",
        name="ADKAR Change Model",
        description="Individual-focused change management model",
        category=FrameworkCategory.CHANGE,
        subcategory="Individual Change",
        when_to_use=[
            "Individual transitions",
            "Team changes",
            "Process improvements",
            "Technology adoption",
            "Skill development",
        ],
        key_components=[
            "Awareness",
            "Desire",
            "Knowledge",
            "Ability",
            "Reinforcement",
        ],
        application_steps=[
            "Create awareness of need",
            "Build desire to change",
            "Provide knowledge/training",
            "Develop ability to change",
            "Reinforce new behaviors",
            "Measure progress",
            "Address gaps",
        ],
        expected_outcomes=[
            "Individual adoption",
            "Behavior change",
            "Skill development",
            "Sustained adoption",
            "Change success",
        ],
        complexity=ComplexityLevel.BASIC,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Change plan",
            "Communication strategy",
            "Training resources",
        ],
        time_to_implement="3-6 months",
        resources_required=[
            "Change managers",
            "Training materials",
            "Reinforcement tools",
        ],
    ),

    "bridges_transition": Framework(
        id="bridges_transition",
        name="Bridges Transition Model",
        description="Framework focusing on psychological transitions during change",
        category=FrameworkCategory.CHANGE,
        subcategory="Transition Management",
        when_to_use=[
            "Organizational transitions",
            "Leadership changes",
            "Restructuring",
            "Culture shifts",
            "Major changes",
        ],
        key_components=[
            "Ending phase",
            "Neutral zone",
            "New beginning",
            "Psychological transitions",
            "Emotional journey",
        ],
        application_steps=[
            "Acknowledge endings",
            "Honor the past",
            "Navigate neutral zone",
            "Support through uncertainty",
            "Launch new beginnings",
            "Celebrate progress",
            "Sustain momentum",
        ],
        expected_outcomes=[
            "Smooth transitions",
            "Emotional support",
            "Reduced resistance",
            "Successful adoption",
            "Cultural integration",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Leadership awareness",
            "Support systems",
            "Communication",
        ],
        time_to_implement="6-12 months",
        resources_required=[
            "Transition team",
            "Support resources",
            "Communication tools",
        ],
    ),

    "lean_change_management": Framework(
        id="lean_change_management",
        name="Lean Change Management",
        description="Agile approach to change using feedback loops and iterations",
        category=FrameworkCategory.CHANGE,
        subcategory="Agile Change",
        when_to_use=[
            "Agile environments",
            "Continuous change",
            "Startup culture",
            "Rapid adaptation",
            "Uncertain outcomes",
        ],
        key_components=[
            "Change canvas",
            "Experiments",
            "Feedback loops",
            "Minimum viable changes",
            "Validated learning",
            "Pivot decisions",
        ],
        application_steps=[
            "Create change canvas",
            "Design experiments",
            "Run small changes",
            "Gather feedback",
            "Learn and adapt",
            "Scale or pivot",
            "Iterate continuously",
        ],
        expected_outcomes=[
            "Adaptive change",
            "Reduced resistance",
            "Faster adoption",
            "Continuous improvement",
            "Learning culture",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "Technology",
            "Startups",
            "Agile organizations",
        ],
        prerequisites=[
            "Agile mindset",
            "Experimentation culture",
            "Feedback systems",
        ],
        time_to_implement="Ongoing",
        resources_required=[
            "Change facilitators",
            "Feedback tools",
            "Experimentation budget",
        ],
    ),

    "appreciative_inquiry": Framework(
        id="appreciative_inquiry",
        name="Appreciative Inquiry",
        description="Positive approach to change focusing on strengths and possibilities",
        category=FrameworkCategory.CHANGE,
        subcategory="Positive Change",
        when_to_use=[
            "Culture transformation",
            "Team building",
            "Vision creation",
            "Organizational development",
            "Morale improvement",
        ],
        key_components=[
            "Define",
            "Discover",
            "Dream",
            "Design",
            "Deploy",
            "Positive focus",
        ],
        application_steps=[
            "Define the positive topic",
            "Discover what works well",
            "Dream of possibilities",
            "Design the ideal state",
            "Deploy changes",
            "Sustain positive momentum",
            "Celebrate successes",
        ],
        expected_outcomes=[
            "Positive engagement",
            "Creative solutions",
            "Higher morale",
            "Sustainable change",
            "Cultural shift",
        ],
        complexity=ComplexityLevel.INTERMEDIATE,
        industry_relevance=[
            "All industries",
        ],
        prerequisites=[
            "Facilitation skills",
            "Stakeholder engagement",
            "Time investment",
        ],
        time_to_implement="3-6 months",
        resources_required=[
            "AI facilitators",
            "Workshop spaces",
            "Communication tools",
        ],
    ),
